packages/core/src/constants/media-sizes.ts, packages/core/src/generators/builder.ts, packages/core/src/parsers/builder.ts
This adds support for responsive styling. I decided to only support jsx-lite -> builder media queries that are `max-width` and pixel based, since when writing back to jsx-lite from builder we convert to that format.
e.g.
```
<div
css={{
width: "100px",
color: "red",
"@media (max-width: 640px)": {
width: "50px",
color: "rgba(54, 70, 175, 1)",
},
}}
> hello </div>
```
Keeping as a draft since it needs more testing!
=> Add support for responsive styles

packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/data/blocks/button.raw.tsx, packages/core/src/__tests__/data/blocks/select.raw.tsx
- Spreading `props.attributes` moved to the start so they don't stomp any explicit component prop
- The Button component was using a regular span, here we use a `button` HTML element
=> Reorder JSX spreads and use `button` for Buttons

packages/core/src/__tests__/__snapshots__/liquid.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/data/blocks/img.raw.tsx, packages/core/src/__tests__/data/blocks/section.raw.tsx, packages/core/src/__tests__/data/blocks/text.raw.tsx, packages/core/src/__tests__/liquid.test.ts, packages/core/src/__tests__/react.test.ts, packages/core/src/__tests__/solid.test.ts, packages/core/src/__tests__/vue.test.ts, packages/core/src/generators/react.ts, packages/core/src/generators/vue.ts, packages/core/src/helpers/collect-styles.ts, packages/core/src/parsers/builder.ts
* Vue: Fixing value interpolation and prop enumeration
* This (for now at least) requires that the `props` param must not be destructured, otherwise members plucked from the props won't be recognized.
* Allow using `innerHTML` JSX-Lite prop (maps to React's `dangerouslySetInnerHTML` and Vue's `v-html`)
* Added the `Text` Builder block
=> Vue Gen fixes + `innerHTML` support

packages/core/src/__tests__/data/blocks/builder-render-block.raw.tsx, packages/core/src/__tests__/data/blocks/builder-render-content.raw.tsx, packages/core/src/index.ts
I think we can absolutely move all of the components into JSX lite
remaining features needing support to get there
- context support (medium)
- onUnmount hook (easy)
- useBuilderData custom async hook (medium)
- [emotion support](https://github.com/egoist/vue-emotion) (medium)
- [dynamic component support](https://vuejs.org/v2/guide/components.html#Dynamic-Components) (easy)
- move logic like stringToFunction, getBlockOptions, applyPatchWithMinimalMutationChain, and getEmotionCss from the react sdk to our utils package (medium)
cc @mandx for our todo list ^ :)
=> RenderBlock and RenderContent drafts

packages/cli/src/cli.ts, packages/cli/src/commands/jsx-lite.ts
Lists all available targets.
```
jsx-lite/packages/cli on  list-command [!]
❯ jsx-lite --list
vue
angular
react
solid
liquid
builder
html
customElement
svelte
jsxLite
template
swift
reactNative
```
=> Add list command to cli

packages/cli/src/cli.ts, packages/cli/src/commands/jsx-lite.ts, packages/cli/src/targets.ts, packages/cli/src/types.ts
- Fix for JSON output
- Clean up cli target list
- Add support for generator options to cli
- Add header flag to cli
Sample output
```
✦ ❯ jsx-lite --to react ../core/src/__tests__/data/basic.raw.tsx --header "// Hello world" --state useState
// Hello world
import { useState } from "react";
export default function MyComponent(props) {
const [name, setName] = useState(() => "Steve");
return (
<>
<div>
<input
value={name}
onChange={(event) => {
setName(event.target.value);
}}
/>
Hello! I can run in React, Vue, Solid, or Liquid!
</div>
</>
);
}
```
=> CLI Generator Options

docs/overview.md
Adds a section for limitations and gotchas to the JSX Lite overview.
Will create another PR that will have some git hooks for formatting markdown on commit which I used for this later.
=> Add gotchas to overview doc

packages/cli/src/commands/jsx-lite.ts
Adds an option to skip running output through prettier. I'm leaving this
undocumented as it's really only useful for debugging jsx-lite at the
moment.
=> Add --prettier flag

packages/cli/package.json, packages/core/package.json
Exports needed this line
".": "./dist/src/index.js"
I tested the fix with
```bash
lerna link --force-local
cd packages/cli
npm run build && ./bin/jsx-lite compile --to react - < ../core/src/__tests__/data/basic.raw.tsx
```
Fixes https://github.com/BuilderIO/jsx-lite/issues/77
=> Add "main" export

packages/cli/scripts/test-new.sh, packages/cli/src/cli.ts, packages/cli/src/commands/new.ts, packages/cli/src/templates/component.lite.tsx.ejs, packages/cli/src/templates/jsx-lite.config.js.ejs, packages/cli/src/templates/tsconfig.json.ejs
Adds a rough first pass at a `new` sub command to generate a jsx-lite
project.
Adds package.json, jsx-lite dependencies, tsconfig, jsx-lite.config.js.
=> Add first pass at `jsx-lite new` sub command

packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/__tests__/cli-integration.test.ts, packages/cli/src/__tests__/data/triptych.builder.json, packages/cli/src/cli.ts, packages/cli/src/commands/compile.ts, packages/core/src/__tests__/builder.test.ts, packages/core/src/generators/qoot.ts
Adds a new flag `--builder-components` that produces portable html output
in place of including react components that only exist within Builder.
BREAKING CHANGE: default output of the compile sub command has changed.
Output would previously always make use of builder custom components,
like `<Image />`, `<Columns />`, etc. Instead, standard html tags and
attributes are generated instead. This behaviour is now opt-in with
`--builder-components` flag.
- fix(cli): use a more specific type
- refactor(cli): don't use require to load string
- fix(cli): remove dead code
- chore: move integration test
- feat(cli): add --builder-components flag
- https://github.com/BuilderIO/jsx-lite/issues/88
=> Remove builder components on compile

packages/core/src/parsers/builder.ts
Since some Builder blocks can contain arbitrary HTML code, valid HTML like:
```html
<p><br></p>
```
Can crash the parsing stage, so this is simple fix to convert that to:
```html
<p><br /></p>
```
So it's safer to parse.
=> Handle HTML void elements when reading/parsing Builder content

packages/core/src/parsers/builder.ts
Sometimes users just left empty Columns around; and while this is fine, this can make the Builder parser to crash because it assumes Columns always have columns...
=> Don't crash when going handling empty Column blocks

packages/core/package-lock.json, packages/core/package.json, packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/generators/builder.ts, packages/core/src/generators/solid.ts, packages/core/src/helpers/get-components-used.ts, packages/fiddle/src/components/Fiddle.tsx
- include props in output
- don't add empty `css` attribute
- only include needed imports
- don't include createMutable if not needed
also:
- removes `debugger` from Fiddle
- disables buggy focus syncing for now from Fiddle
Fixes #98
=> Improvements for SolidJS output

packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/generators/jsx-lite.ts, packages/core/src/generators/qwik.ts
Attributes which have no key are not valid. They should never be part of
the input, but if they are the best is to just ignore them.
=> fix: ignore invalid attributes when generating JSX output

packages/core/src/__tests__/qwik.test.ts, packages/core/src/generators/qwik/component.ts, packages/core/src/generators/qwik/jsx.ts, packages/core/src/generators/qwik/src-generator.ts
- Binding expressions are sometimes statements and need to be converted into IIF.
- `OnMount` code can declare `state` which fails execution. Wrapping it in IIF solves it.
https://builder-io.atlassian.net/browse/ENG-2020
=> fix(qwik): handle statements by wrapping them in IIF.

packages/cli/package-lock.json, packages/cli/package.json, packages/cli/tsconfig.build.json, packages/core/package-lock.json, packages/core/package.json, packages/core/src/internal-types.d.ts, packages/core/tsconfig.build.json, packages/core/typings.d.ts
I noticed mitosis [had quite a big install size](https://packagephobia.com/result?p=%40builder.io%2Fmitosis) (153 MB). This PR removes unneeded library dependencies. Most of them were just moved to `devDependencies` instead. I don't think this will be that big of a decrease but it's a start. 
Note: I think the biggest issue with the package size is that a user has to install the dependencies for every framework even if they're only compiling to one, would be nice if the generators were separated into different packages.
=> remove unneeded dependencies and files

packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/generators/react.ts
We were missing some stateSetter transforms for the `onUpdate` dependencies array :)
=> fix(react): process bindings in onUpdate deps

docs/components.md
we shouldn't show any code using `this` since it can be confusing since the compile code is correct even though the dev code is not correct
onMount(() => {
this.something
})
^ this is a problem
onMount(() => {  <- because of this arrow function `this` should be the global context which is a JavaScript gotcha
this.something
})
the code is compiled correctly but can be confusing and I don't want devs to refactor their code thinking they are fixing a js gotcha 
onMount(function () {  <- because of this arrow function `this` should be the global context which is a js gotcha
this.something
})
=> docs(components): remove this and prefer state

packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/generators/vue.ts
onUpdate dependencies could not be stringified: this caused a bug where changes in objects never caused updates since they are always represented by `[Object object]`. This PR fixes that
=> Fix: Vue onUpdate w/ dependencies

examples/basic/README.md, examples/basic/package.json
Replace `npm` with `yarn` in the readme  setup instructions, because yarn.lock is tracked. This will avoid having yarn.lock and package-lock.json simultaneously which may cause inconsistencies in dependency tree.
=> fix(examples): replace npm with yarn

packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/__tests__/data/blocks/self-referencing-component-with-children.raw.tsx, packages/core/src/__tests__/data/blocks/self-referencing-component.raw.tsx, packages/core/src/__tests__/svelte.test.ts, packages/core/src/generators/svelte.ts
Svelte uses `svelte:self` to reference itself recursively. More about it [here](https://svelte.dev/tutorial/svelte-self).
This PR passes the parent component information to all the child components so that if any of children name match the parents, we introduce Svelte's self tag in place of the component name.
=> fix(svelte): support self-referencing component (#291)

packages/eslint-plugin/src/index.ts
Fix small typo in eslint-plugin index.ts
=> docs(eslint): correct typo in index

packages/cli/src/build/build.ts, packages/cli/src/build/helpers/transpile.ts, packages/core/src/__tests__/__snapshots__/context.test.ts.snap, packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/__tests__/data/context/component-with-context.lite.tsx, packages/core/src/__tests__/svelte.test.ts, packages/core/src/generators/svelte.ts, packages/core/src/generators/vue.ts, packages/core/src/types/config.ts
Vue:
- fixed broken binding for styles `:is='style'`  (was missing quotes)
Svelte:
- add missing else-case logic
- strip state/props refs in `setContext`
CLI:
- add config to set `format` (CJS or ESM) for each target
- fix glob pattern to work with Vue target (since it's deeply nested, e.g. `src/nuxt2/**` instead of `src/**`)
=> Fixes: Svelte & transpilation

packages/cli/src/build/build.ts
We need to make sure to throw errors during `mitosis build`, or else builds will succeed despite certain files not transpiling properly.
=> fix(cli): build - throw errors instead of swallowing

packages/cli/src/build/build.ts
When trying to follow the example I found that no components were compiling for Angular. For some reason the switch statement for Angular was missing. This PR adds it back.
=> Adding back angular component compile

packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/angular.test.ts, packages/core/src/__tests__/data/basic-outputs.raw.tsx, packages/core/src/generators/angular.ts, packages/core/src/helpers/strip-state-and-props-refs.ts
outputs via metadata for now and I'll update the detector later so we won't need useMetadata
```
import { useState, useMetadata, onMount } from '@builder.io/mitosis';
useMetadata({
outputs: ['onMessage', 'onEvent'],
});
export default function MyBasicOutputsComponent(props: any) {
const state = useState({
name: 'PatrickJS',
});
onMount(() => {
props.onMessage(state.name);
props.onEvent(props.message);
});
return <div></div>;
}
```
=> feat(angular): outputs via metadata

packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/angular.test.ts, packages/core/src/__tests__/data/blocks/classname-jsx.raw.tsx, packages/core/src/generators/angular.ts
#353 
Due to the way JSX typings work, we have to account for React Developers who have toolsets that issue warnings for not using className, this then turns into a silent error when compiling to Angular. So to account for this issue we will have the Angular generator account for it. :) :) :)
=> className now gets pruned to class.

.github/workflows/on-push-build.yml, .github/workflows/pr-runner.yml, examples/basic/package.json, examples/todo/package.json, yarn.lock
Use yarn --immutable in CI per docs recommendations.
The previous improvement to include the examples in the workspace already ran them as part of PR build; this further runs them on any commit build.
Future PRs can work toward more complete CI, such as verifying the output code compiles under each supported target, verifying the resulting applications work via Playwright, etc.
=> Build basic and todo examples in CI

.github/workflows/checks.yml, .github/workflows/save-build-artifacts.yml, scripts/mitosis-save-artifacts.ts
- Fix the save artifacts workflow by removing `README.md` file which is no longer present.
- Rename save artifacts workflow to `save-build-artifacts` to make it more clear its purpose.
- Rename `pr-runner` to `checks` to make it more clear its purpose. It runs on both PRs and merge to main repo
=> chore: fix save artifacts workflow; deduplicate workflow;

packages/cli/src/build/helpers/transpile.ts, packages/core/src/generators/react.ts
- Add Fragments in React for root `For` node
- Only use esbuild `.tsx` loader for `.tsx` files, to avoid collisions in TS/TSX syntax.
=> Fix: Transpiler

packages/core/src/helpers/render-imports.test.ts, packages/core/src/helpers/render-imports.ts
Changed the template literal of the renderImport function to allow side-effect imports (e.g. `import 'styles.scss'`).
Made this changes to fix #580 .
=> fix(core): side effect imports

packages/core/src/helpers/babel-transform.ts
onUpdate(() => {
console.log("dddhi");
return () => {
console.log("hello");
};
}, [rootRef, otherRef]);
Causes an error  SyntaxError: unknown: 'return' outside of function. (3:2) 
This "fixes" it. Angular will need to be updated.
=> Add return outside of function.

packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/__snapshots__/context.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/generators/react.ts
Closing issue [609](https://github.com/BuilderIO/mitosis/issues/609)
Added import of React lib to generated components for react.
Without it, generated components after importing them from package are not working due to 
```
ReferenceError: React is not defined
```
More info in linked issue.
=> fix: added import of react for react generated components

packages/core/src/__tests__/__snapshots__/marko.test.ts.snap, packages/core/src/generators/marko/generate.ts
Make sure not to convert `<h1>` to `<h-1>` etc
=> Small marko fix for tag names

docs/components.md, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/generators/vue.ts, packages/core/src/helpers/slots.ts
**Why change is needed?**
`slotIcon={<svg></svg>}` is compiled into `{{slotIcon}}` which isn’t slot, this result in not being able to pass HTML element into slot, it will be displayed as `&lt;svg&gt;...&lt;/svg&gt;`. Named slots should work same as default slot (`props.children`) which is compiled to `<slot></slot>` , therefore named slot should be transpiled into `<slot name="icon"></slot>`. 
**What have been changed?**
I changed parsing prefixed `slotIcon` prop so it will be rendered as `<slot name="icon"/>`
Minor change, self closing `<slot/>` tag instead of `<slot></slot>`
Thank you :)
=> fix(vue): use named slots

packages/cli/package.json, packages/core/package.json, packages/core/src/generators/svelte.ts
components with a style prop should just be passed through, otherwise svelte has compile errors saying this is disallowed
=> fix(svelte): only use use:mitosis_styling for tags, not components

packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/data/default-props/default-props.raw.tsx, packages/core/src/constants/hooks.ts, packages/core/src/index.ts, packages/core/src/parsers/jsx/jsx.ts, packages/core/src/parsers/jsx/props.ts
Refactors the default props feature to use `useDefaultProps` as requested in  https://github.com/BuilderIO/mitosis/issues/650
=> refactor: #650 add useDefaultProps compile away hook

packages/core/src/helpers/babel-transform.ts
`lodash.attempt` swallows errors, which cause our snapshot tests to silently freeze when a failure happens.
- remove `lodash.attempt` usage from babel transform code
- cleanup the code logic a bunch
=> Refactor babel transform to remove lodash.attempt

packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/html.test.ts.snap, packages/core/src/__tests__/__snapshots__/liquid.test.ts.snap, packages/core/src/__tests__/__snapshots__/lit.test.ts.snap, packages/core/src/__tests__/__snapshots__/marko.test.ts.snap, packages/core/src/__tests__/__snapshots__/parse-jsx.test.ts.snap, packages/core/src/__tests__/__snapshots__/preact.test.ts.snap, packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/stencil.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/__tests__/data/blocks/content-slot-jsx.raw.tsx, packages/core/src/generators/vue.ts, packages/core/src/helpers/slots.ts
PR updates prop slots syntax in Vue components used with `<Show>` component.
jsx component
```js
<Show when={props.slotName}>
```
current result
```js
<template v-if="props.slotName">
```
desired output
```js
<template v-if="$slots.name">
```
=> feat(vue): convert prop slots to Vue template slot syntax

packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/generators/svelte.ts
Only export props and not refs.
In svelte `export let` defines a prop.
Before:
After:
=> fix(svelte): only export props / define refs without exporting them

packages/core/package.json, yarn.lock
Move `vue-template-compiler` (used in packages/core/parsers/liquid) from `dependencies` to `peerDependencies`, allowing people to use Mitosis together with Vue 3 packages (otherwise a conflict is raised and they can't be installed). See #316
It was also necessary to add `vue-template-compiler` to the `devDependencies` so that the tests can run.
=> fix(core): move `vue-template-compiler` to peerDependencies (fix #316)

examples/basic/src/blocks/image.lite.tsx, packages/core/src/helpers/get-props.ts
#688 
- throw an Error when js keywords used as props, 
-  js keywords should not be used as var
I get the `prohibitedKeywordRE` from [vue/core](https://github.com/vuejs/core/blob/fa6556a0d56eeff1fec4f948460351ccf8f99f35/packages/compiler-core/src/validateExpression.ts)
=> feat: avoid using JavaScript keyword as property name

packages/cli/src/build/build.ts, packages/core/src/types/config.ts
Pass a second argument containing the path to a custom parser to allow a custom parser to derive the component name.
=> feat: pass path to custom parser

packages/core/src/index.ts
add runtime error if the Mitosis file was compiled through Babel and is imported.
=> refactor(core): useStore runtime error

packages/cli/package.json, packages/core/package.json, packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/generators/qwik/component-generator.ts, packages/core/src/generators/svelte.ts, packages/core/src/index.ts
- fix how generator handles svelte `props.children` refs
- add SDK hack for qwik generator
- add Provider types. Closes https://github.com/BuilderIO/mitosis/issues/706
=> Fix: Qwik SDK hack & svelte props.children refs

packages/core/src/__tests__/__snapshots__/preact.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/generators/react/generator.ts, packages/core/src/generators/svelte.ts, packages/core/src/generators/vue.ts, packages/core/src/parsers/jsx/function-parser.ts
This allows for more basic and imo easier context setting.
For example:
```
import { setContext} from '@builder.io/mitosis';
export default function MyBasicComponent(props) {
setContext('joined', props.joined);
return (
<div>
{props.joined}
</div>
);
}
```
Svelte
Vue
React
=> feat(core): more basic context setting

packages/cli/src/build/build.ts, packages/core/src/types/config.ts
To support Typescript in Sveltosis, we need to preprocess the svelte code first (with https://github.com/sveltejs/svelte-preprocess for example), which is an async fn :)
=> feat(core): allow parser option to be async

packages/cli/src/commands/compile.ts
- In cli compile run, none of the options were passed to the parseJSX function.
- Previously you would have missing types in outputs, if your types were declared outside of the component code
- This is not ideal solution. It should be overridable by user through options. Someone, more well versed in source code should look at it to say from where that option should come
closes https://github.com/BuilderIO/mitosis/issues/782 by the way
=> feat(cli): automatic ts output detection

packages/core/src/__tests__/__snapshots__/vue-composition.test.ts.snap, packages/core/src/generators/vue/compositionApi.ts
Currently only usages of state keys are being appended with `.value` in the Vue 3 composition API generator.  This PR ensures that `.value` is also appended to usages of refs.
- Include Mitosis component ref keys when checking which nodes should have `.value` appended to them
- Added extra checks to ensure `.value` is not appended in watcher definitions, or in function declarations
- Updated snapshots
=> fix(core): append .value to refs when using Vue 3 composition API

packages/core/src/helpers/get-props.ts
Catch more edge cases of prohibited Vue keywords. Applies to all generators, but if that becomes a problem we can scope it to just the Vue generator
=> add prohibited Vue keywords

packages/fiddle/src/components/CodeEditor.tsx
=> fix: MonacoEditor onMount override by props.onMount

packages/cli/src/build/helpers/transpile.ts
If a custom extension is provided in the Mitosis config, it currently only replaces the first match, as the global flag is missing from the regex.
=> fix: transform imports regex

packages/fiddle/src/components/Fiddle.tsx
When Sveltosis is selected as the input tab in the fiddle, we should hide the Svelte output tab.
If it is currently selected, we switch to another tab.
=> fix(fiddle): hide svelte output for sveltosis input

packages/core/src/__tests__/__snapshots__/angular.import.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.mapper.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/data/output-event-bindings.raw.tsx, packages/core/src/__tests__/shared.ts, packages/core/src/generators/angular.ts
[Fix for issue #927](https://github.com/BuilderIO/mitosis/issues/927)
* Angular output event binding requires that the name be camel-cased and rendered with parens when using the prefix `on`. So I removed the `toLowercase()` to keep the camel-case format.
* Added tests with updated snapshots
=> Fix for Issue 927

packages/core/src/__tests__/__snapshots__/angular.import.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.mapper.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/generators/angular.ts
#953 
Remove Browser Module in favor of Common. Add Slot to whitelist as suggested by @samijaber 
Browser Module causes too many issues and while it works for stand alone packages, it ultimately fails when in an app.
Slot added to built-in component white list.
=> Remove Browser Module in favor of Common. Add Slot to whitelist.

packages/fiddle/src/components/Fiddle/Fiddle.tsx
Remove unnecessary padding from the fiddle output menu
Before:
After:
=> Remove padding from output menu

packages/cli/src/build/helpers/extensions.ts, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/generators/solid/blocks.ts, packages/core/src/generators/solid/index.ts
Resolve #583
This code is really similar to the React generator, the only difference is how we handle refs, the [recommended](https://www.solidjs.com/guides/typescript#the-ref-attribute) option for SolidJS is to use an undefined union type and check if the ref is valid before using it, I thought that this would be too complex to implement and choose to use the second recommended option which is using '!' in the ref assignment.
=> Preserve types for SolidJS

packages/cli/package.json, packages/core/package.json, packages/core/src/__tests__/__snapshots__/alpine.test.ts.snap, packages/core/src/generators/alpine/generate.ts
- closes https://github.com/BuilderIO/mitosis/issues/931
- remove `npm` version hack in inner packages, as it caused crashes for end users
- remove positive lookbehind in Alpine, which breaks in Safari
=> Fix: misc bugs

docs/configuration.md
Adds the `MitosisConfig` type definition to the configuration documentation file. Also adds the `Targets` type for more clarity.
fixes Doc request: more about mitosis.config.ts in #493
=> docs(config): add config types for `mitosis.config.js`

packages/cli/src/build/helpers/extensions.ts
I was adding stencil to the list of support for my library and noticed that it only outputs js files even if the typescript flag is explicitly true.
=> fix: add stencil to list of jsx/tsx targets

packages/core/jsx-runtime.d.ts
It seems like the ShapeElementSVGAttributes type erroneously depends on itself, causing a TypeScript warning.
=> fix: jsx recursive type

README.MD
Since there is no support yet for a TypeScript config file, JS comment type hint can help a lot. This PR adds type hint to `README`.
=> Add JS comment type hint for `mitosis.config.js` to `README`

packages/cli/src/commands/compile.ts
Vue needs the option called "api" to be able to choose between composition and options apis
=> Add api option to compile command

packages/core/src/generators/mitosis.ts, packages/core/src/generators/qwik/jsx.ts, packages/core/src/generators/react/generator.ts, packages/core/src/generators/solid/index.ts, packages/core/src/helpers/is-root-text-node.ts
I changed Builder to generate code on a per-selected-block basis. If you select text blocks the code would error out because raw text if rendered at the root needs a fragment around it. This specifically happens only really when created in Builder as Mitosis JSX doesn't let you create root nodes that are text (it's invalid JSX) but builder does allow root text blocks
=> Fix: if root is a text node it needs to be wrapped in a fragment for JSX outputs

packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/generators/qwik/src-generator.ts
Update qwik generator to properly allow `for` attributes instead of forcing them to be `htmlFor`. Fixes #1047
=> support the for attribute in qwik generator

packages/core/jsx-runtime.d.ts
added the property fill to the UseSVGAttributes interface to fix the issue #838
=> add fill property to useSvgAttributes to fix typing

packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/generators/qwik/component-generator.ts, packages/core/src/generators/qwik/component.ts, packages/core/src/generators/qwik/directives.ts, packages/core/src/generators/qwik/jsx.ts
Qwik can get confused when `innerHTML` is used without a `key`, so as a best practice we add `key` there.
=> fix(qwik): add `key` to `innerHTML`.

packages/fiddle/src/components/Fiddle/Fiddle.tsx
- We were not generating TS code properly in the Fiddle. Need to reuse `typescript` state option in the `parseJsx` fn
- Test with `/?outputTab=FYZw9gdkA%3D%3D%3D&code=PTAEAsBdIBwZwFwgOYEtLgK4CMB0BjAewFtgAhTVAGwBMBTAJwEkB5YY9QuVOYbKwtnYBDVADtgMYfgDWw5HV5EGdYHAb5gAfS2RFkODuA1hkYXwGylhKpmJi4uBsIDuuAwA8AUF9TEYhAyQoADeoJhwdADKkIF0ADSgAGKBoAC%2BoABmDCSgAOQAAtiUtIy4qITsnNxweQDcPpAAnjB0oADCNnZioAC8oV6goERieqMIoMJiTQ1DIKAAKiwAIiwTTP5UdMR0o6AYPKAu4LugcJgwAUFZqTRNYsIc%2BB1RUaBUUzRwg0eoNBgAfgmYjs2EYDTSDS8dA8V2C4j0DEy0janVs9gACjl4AMhkR0Q4gR0uvYANoAXShczAS1W602212wQOcCOJx650ugWCmVu90eqGe7Ve70%2B3yGcCk%2BDoRJBxDBDFmoHmtLWoA2MC2Oz2LLZp05cJuDFAdweTxebw%2BYi%2BPzgZlkaO6cAAgpAiXkzPw6JA8qAAD75YiCah0X0BvJiOgAN0Y9R%2BKpWao1WqZ%2B3Ah2O%2Bouht5xtNAqFIqtNqGKhjDEijvscAA6uyYtIZHQaETsIQbHQphCfDDDfRkZgqDzMGJ8JAKj0q2IA …
=> Fix: use TS option in Fiddle JSX

packages/cli/src/helpers/get-mitosis-config.ts
When passing a custom config file, either with `js` or `cjs` extension, to the CLI, the "No config file found for Mitosis" was shown.
This is a fix, that preserves the original approach with the additional edge case of a custom config file handled properly.
NOTE: The imports were automatically organized by `vs-code` with `organizeImports` function.
=> fix: no config file found for Mitosis

packages/core/jsx-runtime.d.ts
- what changes you made:  add missing  svg attribute `xmlns`
=> fix: add missing  svg attribute xmlns

packages/cli/src/helpers/get-mitosis-config.ts, packages/core/src/__tests__/__snapshots__/alpine.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.import.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.mapper.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/html.test.ts.snap, packages/core/src/__tests__/__snapshots__/liquid.test.ts.snap, packages/core/src/__tests__/__snapshots__/lit.test.ts.snap, packages/core/src/__tests__/__snapshots__/marko.test.ts.snap, packages/core/src/__tests__/__snapshots__/parse-jsx.test.ts.snap, packages/core/src/__tests__/__snapshots__/preact.test.ts.snap, packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/rsc.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/stencil.test.ts.snap, packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/__tests__/__snapshots__/taro.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue-composition.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/__tests__/data/nested-styles.raw.tsx, packages/core/src/helpers/styles/collect-css.ts
This PR fixes the unnecessary whitespace added to the output CSS when not using `&` for pseudo-classes and selectors.
Closes #1125
=> fix: css pseudo classes and selectors

packages/cli/src/__tests__/__snapshots__/cli-integration.test.ts.snap, packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/__tests__/builder.test.ts, packages/core/src/parsers/builder/builder.ts
=> fix(qwik): fix missing class attribute

packages/core/src/__tests__/__snapshots__/vue-composition.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/generators/vue/compositionApi.ts, packages/core/src/generators/vue/optionsApi.ts
- what changes you made,   add classStringToObject types for better ts check.
js
```js
_classStringToObject(str) {
const obj = {};
if (typeof str !== "string") {
return obj;
}
const classNames = str.trim().split(/\s+/);
for (const name of classNames) {
obj[name] = true;
}
return obj;
},
```
ts
```ts
_classStringToObject(str: string) {
const obj: Record<string, boolean> = {};
if (typeof str !== "string") {
return obj;
}
const classNames = str.trim().split(/\s+/);
for (const name of classNames) {
obj[name] = true;
}
return obj;
},
```
=> fix(vue): add classStringToObject types if typescript

packages/cli/src/build/helpers/context.ts, packages/core/src/generators/context/react.ts
This PR ensures that context generation imports from Preact rather than React in Preact generation
Fixes #1163
=> fix: preact context generation imports from proper library

packages/core/package.json, packages/core/src/types/metadata.ts
=> Fix core package

packages/core/src/__tests__/__snapshots__/vue-composition.test.ts.snap, packages/core/src/generators/vue/compositionApi.ts
=> fix(core): fix onUpdated missing {} in vue

packages/cli/src/__tests__/__snapshots__/cli-integration.test.ts.snap, packages/core/src/__tests__/__snapshots__/context.test.ts.snap, packages/core/src/__tests__/__snapshots__/preact.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/rsc.test.ts.snap, packages/core/src/__tests__/__snapshots__/taro.test.ts.snap, packages/core/src/generators/react/generator.ts, packages/core/src/generators/rsc.ts
for react, we are blanket adding "use client" nearly everywhere. in most cases, we do not want this. react native and preact should never have it, and any component without client only hooks or event listeners shouldn't have it either
=> only add "use client" when needed

.gitattributes
GitHub also highlights comments in json as errors by default.  Adding the following to  `.gitattributes` stops that.
```
*.json  linguist-language=JSON-with-Comments
```
Makes project readme prettier on github.
Other possibilities discussed here:
https://github.com/microsoft/rushstack/issues/1088
=> chore: stop GitHub highlighting comments in json as errors

.yarn/versions/3cb89724.yml, packages/cli/package.json, packages/core/package.json, packages/core/src/helpers/plugins/process-signals.ts
=> fix React Native signals

developer/README.md, package.json, packages/cli/package.json, packages/core/package.json, yarn.lock
- `rm -rf` doesn't work for windows user 😥
- [`rimraf`](https://www.npmjs.com/package/rimraf) should solve this issue for every OS
=> fix: add rimraf to enable build & e2e tests for windows users

package.json, yarn.lock
The current `Mitosis` will throw out error when compiling the `typescript` codes that include `satisfies` operator. 
```
ERROR: Expected ";" but found "satisfies"
```
Need to upgrade `esbuild` to fix that.
https://github.com/remix-run/remix/issues/4639
=> fix: update esbuild to fix typescript "satisfies" not supported issue

packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/generators/solid/index.ts
Remove unnecessary import of "solid-styled-components"
Mitosis will now wrongfully add `import { css } from "solid-styled-components` in generated `Solid` components when `styleType` attribute is set as "style-tag" in `mitosis.config.js` like this:
```javascript
// mitosis.config.js
solid: {
stylesType: 'style-tag'
}
```
Mitosis will only add `import { css } from "solid-styled-components"` when there are style code in `Mitosis jsx` and `styleType` attribute is set as "styled-components"
This PR will fix the issue and make it behave as expected.
=> fix: remove unnecessary import of "solid-styled-components"

packages/core/src/parsers/builder/builder.ts
we have code for converting Builder.io content to Mitosis where we skip simple unstyled wrapper divs around text
we neglected tho to make sure we don't skip (aka gobble) layers that have other important things - like components, properties, or bindings
this should fix this, making sure we only eat parents around text if they are purely a `<div>` tag with no style, properties, component, etc as originally intended
=> don't eat text node wrappers that have components, bindings, or properties

.changeset/late-trees-arrive.md, packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/generators/qwik/helpers/add-prevent-default.ts, packages/core/src/generators/qwik/src-generator.ts
This PR updates the `preventDefault` logic for Qwik by:
- removing `=""` from `preventdefault:eventName=""`
- removes any occurrences of `(event*).preventDefault();` inside the handler
For example test,
```jsx
import { useState } from '@builder.io/mitosis';
export default function MyComponent(props) {
const [name, setName] = useState('Steve');
return (
<div>
<input
value={name}
onChange={(event) => {
event.preventDefault();
setName(event.target.value);
}}
/>
Hello! I can run in React, Vue, Solid, or Liquid!
</div>
);
}
```
gives output,
```jsx
import { $, Fragment, component$, h, useStore } from "@builder.io/qwik";
export const MyComponent = component$((props) => {
const state = useStore({ name: "Steve" });
return (
<div>
<input
preventdefault:change
value={state.name} …
```
=> [fix] `preventDefault` in Qwik

.changeset/funny-starfishes-talk.md, .changeset/strange-pillows-love.md, examples/basic/src/blocks/button.lite.tsx, packages/core/src/__tests__/__snapshots__/alpine.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.import.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.mapper.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/context.test.ts.snap, packages/core/src/__tests__/__snapshots__/html.test.ts.snap, packages/core/src/__tests__/__snapshots__/liquid.test.ts.snap, packages/core/src/__tests__/__snapshots__/lit.test.ts.snap, packages/core/src/__tests__/__snapshots__/marko.test.ts.snap, packages/core/src/__tests__/__snapshots__/parse-jsx.test.ts.snap, packages/core/src/__tests__/__snapshots__/preact.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/rsc.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/stencil.test.ts.snap, packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/__tests__/__snapshots__/taro.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue-composition.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/generators/react/blocks.ts, packages/core/src/helpers/filter-empty-text-nodes.ts, packages/core/src/helpers/is-root-text-node.ts, packages/core/src/parsers/jsx/jsx.ts, packages/fiddle/src/components/Fiddle/Fiddle.tsx
Reverts BuilderIO/mitosis#1357
=> Bring back "Fix: redundant empty nodes""

.changeset/sharp-sloths-fly.md, packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/generators/svelte/blocks.ts, packages/core/src/generators/svelte/svelte.ts
This PR directly attaches styles to the `style` attribute of an element and as objects cannot be directly assigned to the `style` attribute we are using: [stringifyStyles](https://github.com/sveltejs/svelte/issues/7311#issuecomment-1049514519)
**Loom**
https://www.loom.com/share/d019ee52a0ed454cac49ab70cbb784f5
the `--var` support,
Closes https://github.com/BuilderIO/builder/issues/3190
**Jira**
https://builder-io.atlassian.net/browse/ENG-5640
=> fix: svelte styling to apply during ssr

.changeset/slimy-emus-bake.md, packages/core/src/__tests__/__snapshots__/context.test.ts.snap, packages/core/src/__tests__/__snapshots__/preact.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/rsc.test.ts.snap, packages/core/src/__tests__/__snapshots__/taro.test.ts.snap, packages/core/src/generators/react/blocks.ts
This PR fixes empty fragments in React generator when we use `<>text</>`
Mitosis link: https://mitosis.builder.io/?outputTab=E4UwhgxgLkA%3D&code=KYDwDg9gTgLgBAE2AMwIYFcA29noHYDGMAlhHnALICeAwhALaR7B4wAUYUEYAzgJRwA3gCg4cKMBjoo5NqLFwAPAD55CgBbBMmCGqUB6VWL4BuYQF8gA
=> fix: empty react fragment with text

.changeset/quick-cows-change.md, packages/core/src/__tests__/__snapshots__/context.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/data/react-native/onclick-to-pressable.raw.tsx, packages/core/src/__tests__/test-generator.ts, packages/core/src/generators/react-native/index.ts, packages/core/src/generators/react/blocks.ts, packages/core/src/generators/react/generator.ts
This PR converts any `View` with onClick event attached to a `Pressable` and converts the `onClick` to `onPress` so that its handled properly inside React Native
**Jira**
https://builder-io.atlassian.net/browse/ENG-5713
**Loom**
https://www.loom.com/share/bf63014d0a6346bb878c8f2f8be50b98
=> [feat] support `onClick` events in RN with Pressable

.changeset/witty-keys-flow.md, packages/core/src/__tests__/__snapshots__/angular.mapper.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.styles.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/angular.styles.test.ts, packages/core/src/generators/angular/index.ts, packages/core/src/generators/angular/types.ts
In this PR, we are adding a new option called `visuallyIgnoreHostElement` which attaches `display: contents;` to the host angular element, which means they will now just be considered as decoration element and will not interfere with dom stylings in any way. 
> Why is this needed? Refer: https://stackoverflow.com/questions/34280475/remove-the-host-html-element-selectors-created-by-angular-component/52292365#52292365
> `display: contents` causes an element's children to appear as if they were direct children of the element's parent, ignoring the element itself. This can be useful when a wrapper element should be ignored when using CSS grid or similar layout techniques.
- Go to [angular.dev](https://angular.dev/) playground
- Use this code snippet,
```ts
import {Component} from …
```
=> feat: `visuallyIgnoreHostElement` option for angular to apply `display: contents`

.changeset/twenty-cheetahs-carry.md, packages/starter/template/library/package.json
This PR is related to issue #1444
The launch of command `npm run start` failed on windows because of the single quote inside the command start in the `package.json`:
```json
"start": "watch 'npm run build' ./src",
```
To make it work on windows too, it is enough to replace them with escaped double quotes
This small fix solves the problem and allows it to be run on windows too.
=> fix: npm run start script on win

packages/docs/src/routes/docs/using-libraries/index.mdx
Correct typo in using-libraries of docs
=> fix(docs): correct typo in using-libraries

packages/docs/src/routes/docs/components/index.mdx
fixes some spelling and grammar issues in the docs. also clarified the points about `<Show>` since it was confusing.
=> improve docs - fix spelling and grammar & clarify some points

packages/docs/src/routes/docs/quickstart/index.mdx
- Rename the variable `e` to `event` in the code sample to conform to the [`jsx-callback-arg-name`](https://github.com/morinokami/mitosis/blob/main/packages/eslint-plugin/src/rules/jsx-callback-arg-name.ts) rule
- Correct the path to the Greet component to match [the path instructed to create this component](https://github.com/morinokami/mitosis/blob/main/packages/docs/src/routes/docs/quickstart/index.mdx?plain=1#L45)
=> docs: update quickstart/index.mdx

.changeset/rotten-camels-wash.md, packages/core/package.json, packages/core/src/generators/vue/optionsApi.ts, packages/core/src/generators/vue/types.ts, yarn.lock
Remove 2 deprecated dependencies: `vue` and `@babel/plugin-proposal-class-properties`
- Vue has already has its v2 version deprecated.
- `@babel/plugin-proposal-class-properties` is deprecated, which can be seen in [here](https://www.npmjs.com/package/@babel/plugin-proposal-class-properties).
There are just 1 place in core's code to import vue for its ts definition. So we could copy them and remove the import of `vue2`
As there were 0 places to import `@babel/plugin-proposal-class-properties`, we could just remove the import of it.
=> fix: remove 2 deprecated dependencies in core package

.changeset/strong-cycles-cough.md, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/data/react-native/twrnc-styled-component.raw.tsx, packages/core/src/__tests__/react-native.test.ts, packages/core/src/generators/react-native/index.ts, packages/core/src/generators/react/generator.ts, packages/core/src/generators/react/types.ts
- What changes you made: 
- Adds support for [twrc ](https://github.com/jaredh159/tailwind-react-native-classnames)and [native-wind](https://www.nativewind.dev/) styling to the react-native target
- Why you made them, and: 
- It will allow users more freedom to style their components, specially if they use a tailwind-based style system, that way they can share their style preset across all generator types
=> feat: react-native "twrnc" and "native-wind" styling types

packages/core/package.json, yarn.lock
neotraverse/legacy wouldn't work with Webpack 4 and before as is, as webpack 4 doesn't support export maps. v0.6.12 provides fallback for that as a top level legacy.js file.
Edit: Bumped to 0.6.15, comes with better TypeScript support(irrelevant to this PR, just good to be on the latest), lower NodeJS support
=> chore: Bump neotraverse to 0.6.15

.changeset/rude-garlics-impress.md, packages/core/src/__tests__/__snapshots__/angular.import.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.mapper.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.state.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.styles.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/data/angular/state-init-sequence.raw.tsx, packages/core/src/__tests__/test-generator.ts, packages/core/src/generators/angular/index.ts
sequence matters first initialize state then binding states else we will not get the correct value as angular states are not reactive and not re-trigger any computed values
=> fix: state init in angular in correct sequence

package.json
Replaces `'` with `\"` in package.json
Single quotes doesn't work on Windows.
closes #1444
=> fix: issue with single quotes in package.json not working for windows

.changeset/small-shrimps-vanish.md, packages/core/src/helpers/is-upper-case.ts
While parsing JSX, it's possible that it received an invalid or undefined tag. For the most part this is fine and mitosis handles this, except internally there's one scenario where it crashes when trying to uppercase the undefined tag. This PR just does a double check that the value is a valid string.
=> fix: check string value in isUpperCase

.changeset/fast-rivers-search.md, packages/core/src/generators/builder.ts
Ensure that we found a suffix before trying to test if its uppercase.
=> fix: ensure component name suffix

.changeset/famous-pumas-shop.md, packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/builder.test.ts, packages/core/src/__tests__/data/builder/text-bindings.json, packages/core/src/generators/builder.ts, packages/core/src/parsers/builder/builder.ts
Converting Builder content to Mitosis currently crashes given a Text node with a stringified binding. This is happening because Builder uses a `{{ }}` syntax for bindings, but Mitosis expects a `{ }` format. This PR fixes the issue by converting `{{ }}` to `{ }` when going from Builder --> Mitosis and by converting `{ }` to `{{ }}` when going from Mitosis --> Builder for Text nodes.
=> fix: do not crash on Text node with bindings

packages/docs/src/routes/docs/hooks/index.mdx
Add a note in documentation for `useRef`:
Avoid using `const ref = useRef(null);`, beacuse it might be a conflict with `Vue`.
=> docs: note for useRef hook to avoid naming it "ref" -> conflict with vue

.changeset/nice-teachers-glow.md, .changeset/smooth-moose-wash.md, packages/core/src/__tests__/__snapshots__/alpine.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.import.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.mapper.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.state.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.styles.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/html.test.ts.snap, packages/core/src/__tests__/__snapshots__/liquid.test.ts.snap, packages/core/src/__tests__/__snapshots__/lit.test.ts.snap, packages/core/src/__tests__/__snapshots__/marko.test.ts.snap, packages/core/src/__tests__/__snapshots__/parse-jsx.test.ts.snap, packages/core/src/__tests__/__snapshots__/preact.test.ts.snap, packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/rsc.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/stencil.test.ts.snap, packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/__tests__/__snapshots__/taro.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue-composition.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/__tests__/data/basic.raw.tsx, packages/core/src/parsers/jsx/element-parser.ts
```
import { useState } from "@builder.io/mitosis";
export default function MyComponent(props) {
const [name, setName] = useState("Steve");
return (
<div>
-&gt;
</div>
);
}
```
this is a perfectly valid JSX component that generated broken code for all frameworks
=> fix: keep escaped string on _text

.changeset/lemon-melons-build.md, packages/core/src/__tests__/__snapshots__/angular.import.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.mapper.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.state.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.styles.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/preact.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/rsc.test.ts.snap, packages/core/src/__tests__/__snapshots__/taro.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue-composition.test.ts.snap, packages/core/src/helpers/get-typed-function.ts
Add [`ReturnType<...>`](https://www.typescriptlang.org/docs/handbook/utility-types.html#returntypetype) to `packages/core/src/helpers/get-typed-function.ts`.
We don't want to return the complete function as a return type. Instead we want to return the return type of the function. 
=> fix: issue with functions in `useStore` for typescript

.changeset/lemon-hornets-laugh.md, .github/workflows/checks.yml, CONTRIBUTING.md, packages/core/src/__tests__/__snapshots__/alpine.test.ts.snap
Add a new job in workflows to regenerate snapshots if the tests fail.
This would allow contributors to download the artifact with the snaphots, no matter which environment they use locally.
=> feat: add job to regenerate snapshots in ci

.changeset/warm-lobsters-nail.md, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/generators/solid/blocks.ts
=> Solid: fix Fragment w/ `key` prop

.changeset/violet-kangaroos-sing.md, packages/core/src/__tests__/builder.test.ts, packages/core/src/parsers/builder/builder.ts
https://builder-io.atlassian.net/browse/ENG-7491
Bound media query styles are not preserved when converting Builder to Mitosis. This PR addresses the problem by ensuring that bound media query styles are included in the Mitosis node when bound using `responsiveStyles.[SIZE].[CSS PROP]`.
=> fix: preserve bound media query styles when converting builder to mitosis

packages/docs/package.json, yarn.lock
=> upgrade mitosis in site

.changeset/shy-windows-rest.md, packages/core/src/__tests__/builder.test.ts, packages/core/src/parsers/builder/builder.ts
Bound media query styles in the Builder parser are incorrectly transformed into strings. This means that `color: state.color` becomes `color: "state.color"` and the color prop on an element is set to the `"state.color"` string literal instead of being evaluated to the value of `state.color`.
This PR fixes the issue by ensuring that bound values remain bound and are not converted to strings.
=> fix: bound media query styles are not converted to strings

.changeset/itchy-chairs-collect.md, packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/builder.test.ts, packages/core/src/parsers/builder/builder.ts
Adds null check for property values
https://www.loom.com/share/be7a4cd800614433aaa82b7675b87bd8
https://builder-io.atlassian.net/browse/ENG-8150
=> Null check

.changeset/breezy-tips-scream.md, packages/core/src/__tests__/builder.test.ts, packages/core/src/parsers/jsx/element-parser.ts
Mitosis currently does not account for JSX fragments for slot generation when going from Mitosis JSX --> Mitosis JSON: [Playground](https://mitosis.builder.io/playground/?code=FAUwHgDg9gTgLgAgCYgGYEMCuAbRrMB2AxnAJZQEICyAngMJQC20BIBcAFBDFBAM4BKBAG9gCBDBBxMMShzHiEAHgBiUKAkY0ACjwgBeUYsVKAfAuPilAIUxw4FBAHpzl5S4sIAvs9cIBANzAXkA) (click "json" as the output). When generating outputs such as Builder Content, this causes a crash as data inside of custom components are not being bound correctly.
However, when passing in a JSX Element directly, Mitosis generates slots with the JSX element: [Reproduction](https://mitosis.builder.io/playground/?code=FAUwHgDg9gTgLgAgCYgGYEMCuAbRrMB2AxnAJZQEICyAngMJQC20BIBcAFBDFBAM4BKBAG9gCBDBBxMMShzHiEAHgBiUKAkY0ACjwgBeUYsVKAfAuPilAIUxw4FBAHpzl5S4sIAvs9cIBANzAXkA) …
=> fix: parseJsx accounts for JSX fragments when generating slots

.changeset/old-dots-design.md, packages/core/src/parsers/builder/builder.ts
Checking for a null string
Null values were being passed in for width
=> [ENG-8183] Checking for a null value

.changeset/flat-days-protect.md, packages/core/src/__tests__/builder.test.ts, packages/core/src/generators/builder/generator.ts
The Builder generator does not include the `width` values when going from Mitosis --> Builder. This results in column objects with in the Columns component having the wrong size. See results from the test pushed to this branch:
**Input**
```js
{
data: {
blocks: [
{
'@type': '@builder.io/sdk:Element',
component: {
name: 'Columns',
options: {
columns: [{ blocks: [], width: 50 }, { blocks: [] }],
},
},
},
],
},
}
```
**Results**
```diff
FAIL  src/__tests__/builder.test.ts > Builder > map Column widths
Error: Snapshot `Builder > map Column widths 1` mismatched
- Expected
+ Received
{
"data": {
"blocks": [
{
"@type": "@builder.io/sdk:Element",
"actions": {},
"bindings": {},
"children": [],
"code": {
"actions": {},
"bindings": {},
},
"component": {
"name": "Columns",
"options": {
"columns": [
{ …
```
=> fix: Builder generator includes width on Columns components

.changeset/shy-bears-invent.md, packages/core/src/__tests__/builder.test.ts, packages/core/src/generators/builder/generator.ts
When [fixing an issue where dynamic styles were not mapped to bindings](https://github.com/BuilderIO/mitosis/commit/a38e5bb4bcdeb4c77a8f4ae36ffa5cba993b4cc4) I inadvertently broke a usecase where a function call could be bound to get the styles (I.e. `style={state.getStyles()}`. This PR resolves the issue by ensuring that call expressions can be set as styles.
It's possible that I am missing other use cases here, so I added a console warning whenever invalid styles are dropped so it's a bit more obvious that this is happening in the future.
Failing test example:
```diff
FAIL  src/__tests__/builder.test.ts > Builder > preserve bound call expressions for styles
Error: Snapshot `Builder > preserve bound call expressions for styles 2` mismatched
- Expected
+ Received
{
"@type": …
```
=> fix: bound call expression styles are preserved in Builder generator

.changeset/rich-turkeys-smoke.md, packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/builder.test.ts, packages/core/src/parsers/builder/builder.ts
The Builder JSON parser currently strips out falsey style values (I.e. `padding: 0`). The original motivation for this was to cut down on the amount of CSS generated with codegen in Builder. However, our codegen process has improved since then where this is not a big problem anymore.
More importantly, stripping falsey values is causing functional changes to the code because we make the assumption that a value of `0` is the same as not having the CSS declaration to begin with which is not always true. For example, we remove values such as `flex-shrink: 0`. However, the [default value for `flex-shrink` is 1](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-shrink#formal_definition).
Another example can be seen here: https://codepen.io/liamdebeasi/pen/gbOrgJm
In the first block `#text` …
=> fix: Builder parser does not strip falsey style values

.changeset/sixty-oranges-tie.md, e2e/e2e-app/src/component-paths.ts, e2e/e2e-app/src/components/component-on-update.lite.tsx, e2e/e2e-app/src/homepage.lite.tsx, e2e/e2e-app/tests/main.spec.ts, e2e/e2e-react/src/App.tsx, packages/core/src/__tests__/__snapshots__/stencil.test.ts.snap, packages/core/src/generators/stencil/component.ts, packages/core/src/generators/stencil/helpers/index.ts
Dependencies from `onUpdate` hook weren't used inside `componentDidUpdate`. By using `@Watch` we can generate a similar solution for `onUpdate` hook with dependencies.
=> feat: add dependency handling for onUpdate hook

.changeset/silly-cheetahs-tickle.md, packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/builder.test.ts, packages/core/src/generators/builder/generator.ts
The Builder generator maps options for Builder components to both `component.options` and `bindings`. [Example](https://mitosis.builder.io/playground/?code=KYDwDg9gTgLgBAE2AMwIYFcA29noHYDGMAlhHnALICeAwhALaR7B4wAUYUEYAzgJRwA3gCg4cKMBjoo5NqLFwAPAEl6qAObA4qHmGBEASqhIQAvIICMAXzgB6AHzy%2BAbmFWgA%3D%3D%3D)
In the example above, notice how `aspectRatio` appears on both `component.options` and `bindings['component.options.aspectRatio']`.
The Builder generator loops through any component props and [either puts them on `component.options` or `bindings`](https://github.com/BuilderIO/mitosis/blob/57f371d409d2c0167aebe0ea82431b554efc3948/packages/core/src/generators/builder/generator.ts#L606-L611).
However, we later loop through the component props again and then [put them on …
=> fix: Builder generator does not create duplicate component option mappings

.changeset/fresh-bulldogs-judge.md, packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/generators/svelte/blocks.ts
- **What changes you made:**  
I updated `svelteToBlock` to handle the `key` attribute differently for Svelte due to its unique syntax requirements.  
- **Why you made them:**  
Svelte uses a distinct syntax for managing keyed each blocks, and the previous implementation was not compatible, causing issues when dynamically updating content.  
- **Any other useful context:**  
This change ensures proper handling of component updates in Svelte by aligning the `key` management with Svelte's syntax, preventing reactivity issues.
=> Handle key attribute correctly for Svelte

.changeset/heavy-forks-compare.md, packages/core/src/__tests__/__snapshots__/mitosis.test.ts.snap, packages/core/src/__tests__/mitosis.test.ts, packages/core/src/generators/mitosis/generator.ts
I left the check intentionally minimal to the cases we know we encounter right now to not inadvertently break anything
=> Don't output JSX attributes for Mitosis generator that are invalid (eg. start with @ or :)

.changeset/neat-knives-search.md, packages/core/src/__tests__/__snapshots__/stencil.test.ts.snap, packages/core/src/generators/stencil/helpers/index.ts
I've made a mistake by using the `ReturnType` of a function for EventEmitter, which will be `void` in most cases.
In fact we try to use the parameters of the functions for the `EventEmitter`.
=> fix: issue with stencil event type

.changeset/unlucky-planes-compete.md, packages/core/src/__tests__/mitosis.test.ts, packages/core/src/generators/mitosis/generator.ts
The code in the included test causes prettier to crash due to its use of the typescript parser. When deciding if we need to escape characters, we previously used the babel parser. However, that does not crash on this code. As a result, I updated this flow to use the typescript parser via prettier to check if we need to do any escaping.
Open to other ideas for how to do this, this just seemed like the best way to fix the issue while making minimal changes.
=> fix: < and > are properly escaped when generating JSX

.changeset/purple-stingrays-invite.md, packages/core/src/__tests__/builder/symbols.test.ts, packages/core/src/parsers/builder/builder.ts
Symbol data is not being preserved when parsing as Mitosis. As a result, when going back to Builder JSON the symbol data is not there which causes rendering problems.
=> fix: Builder Symbol information is preserved

packages/core/src/__tests__/__snapshots__/context.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/generators/react/generator.ts, packages/core/src/generators/react/helpers/state.ts
Limit imports in ReactNative to only include used components and to not import components from React Native that are already imported from elsewhere.
https://builder-io.atlassian.net/browse/ENG-9380
=> Only import used ReactNative components

packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/generators/react/helpers/state.ts
A follow up to https://github.com/BuilderIO/mitosis/pull/1760 that corrects use of `Linking` and `StyleSheet`.
=> add fix for Stylesheet and Linking

.changeset/thirty-melons-hammer.md, packages/core/src/__tests__/builder/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/builder/builder.test.ts, packages/core/src/generators/builder/generator.ts, packages/core/src/generators/builder/types.ts, packages/core/src/helpers/get-state-object-string.ts, packages/core/src/parsers/builder/builder.ts
- Correctly convert `For` loop in Mitosis JSX to `repeat.collection` in Builder JSON 
-  Mitosis JSX
```
<For each={[1,2,3]}>
<div>Hello</div>
</For>
```
Currently the `For` loop in Mitosis JSX is converted to the following in Builder JSON
Builder JSON within a builder block
```
"repeat": {
"collection": "[1, 2, 3]"
},
```
Which is not valid builder JSON, and it should be assigned a value in the `data.state` object in Builder JSON. This PR corrects the conversion so that the `repeat.collection` property is populated correctly. 
=> feat: ENG-9092 Correctly convert `For` loop in Mitosis JSX to `repeat.collection` in Builder JSON

.changeset/funny-donuts-mate.md, packages/core/src/__tests__/builder/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/builder/builder.test.ts, packages/core/src/generators/builder/generator.ts
- For symbols or custom components which has a self reference within it's definition, we will remove the self reference a
- The `componentToBuilder` generator outputs a Javascript Object instead of a string. When we try to JSON.stringify the builder json object, it throws a circular reference error. It causes error in the `builderContentToMitosisComponent` https://github.com/BuilderIO/mitosis/blob/main/packages/core/src/parsers/builder/builder.ts#L1218
=> feat: ENG-9021 Remove Circular References for `componentToBuilder` generator

.changeset/kind-steaks-study.md, packages/core/src/generators/builder/generator.ts, packages/core/src/parsers/builder/builder.test.ts, packages/core/src/parsers/builder/builder.ts
- if the component name contains a colon, store the original name in `meta` 
- during `componentToBuilder` transpilation use the original name in `meta` as the component name.
- VE AI removes the colon from the component names 
=> fix: ENG-9776 AI feature not working because of custom component name which includes colon
