README.MD
This project looks awesome, looking forward to v1!
=> little bitty typo

packages/core/src/parsers/builder.ts
Add support for text nodes to have responsive styles
=> Text node support for responsive styles

packages/fiddle/src/components/Fiddle.tsx
Make the code panels resizable
=> Add resizable panels

packages/core/src/__tests__/__snapshots__/liquid.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/data/blocks/video.raw.tsx, packages/core/src/__tests__/liquid.test.ts, packages/core/src/__tests__/react.test.ts, packages/core/src/__tests__/solid.test.ts, packages/core/src/__tests__/vue.test.ts, packages/core/src/generators/builder.ts, packages/core/src/generators/html.ts, packages/core/src/generators/react-native.ts, packages/core/src/generators/react.ts, packages/core/src/generators/swift-ui.ts, packages/core/src/helpers/collect-styles.ts, packages/core/src/helpers/getters-to-functions.ts, packages/core/src/helpers/has-component.ts, packages/core/src/helpers/has-props.ts, packages/core/src/helpers/is-component.ts, packages/core/src/helpers/traverse-nodes.ts, packages/core/src/plugins/compile-away-components.ts, packages/fiddle/src/components/Fiddle.tsx
Currently WIP until I figure out a way to use effects (some props are supposed to be used as "boolean" attributes; as in, the attribute must be added or removed, not just set to `true` or `false`.
Unsure if this is even possible, since this quirk is highly specific to HTML; I guess it breaks the abstraction a bit...
=> First pass at the video block

packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/generators/react.ts, packages/core/src/parsers/jsx.ts, packages/core/src/types/jsx-lite-component.ts
=> afterRender (useEffect) hook

packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/generators/react.ts, packages/core/src/parsers/jsx.ts, packages/core/src/types/jsx-lite-component.ts
agree Vue's hooks names are the best so far so standardizing on that feels right @mandx
=> rename afterRender hook -> onMount

packages/core/src/generators/html.ts, packages/core/src/helpers/babel-transform.ts, packages/core/src/helpers/get-state-object-string.ts
=> Webcomponents codegen testing and debugging

packages/core/src/generators/angular.ts, packages/core/src/generators/html.ts, packages/core/src/generators/jsx-lite.ts, packages/core/src/generators/react.ts, packages/core/src/generators/svelte.ts, packages/core/src/generators/vue.ts, packages/core/src/index.ts, packages/core/src/types/jsx-lite-component.ts
Maybe has some problems, but I think it's a good starting point to revisit/improve later.
This is mostly needed to cleanup DOM event listeners.
=> A probably buggy `onUnMounted` hook implementation

packages/cli/src/commands/jsx-lite.ts
Fix for anything that outputs JSON, mainly the "builder" target.
Previous output:
```json
{
data: {
jsCode: 'Object.assign(state, { name: "Steve" });\n',
tsCode: 'useState({ name: "Steve" });\n',
blocks: [ [Object] ]
}
}
```
Now:
```json
{
"data": {
"jsCode": "Object.assign(state, { name: \"Steve\" });\n",
"tsCode": "useState({ name: \"Steve\" });\n",
"blocks": [
{
"@type": "@builder.io/sdk:Element",
"tagName": "div",
"code": {
"actions": {}
},
"properties": {},
"bindings": {},
"actions": {},
"children": [
{
"@type": "@builder.io/sdk:Element",
"tagName": "input",
"code": {
"actions": {
"change": "state.name = event.target.value"
}
},
"properties": {},
"bindings": {
"value": "state.name"
},
"actions": {
"change": "state.name = event.target.value"
},
"children": []
},
{
"@type": …
```
=> Fix for JSON output

packages/cli/readme.md, packages/cli/src/cli.ts, packages/cli/src/commands/jsx-lite.ts
Lets users input builder, jsxlite or liquid content.
=> Add --from flag to cli

README.MD
Hey there,
I was checking out the repo and thought I'd help out by updating some of the copy in the README.
=> Docs: Small corrections and consistency updates on the README

packages/core/package.json, packages/core/src/parsers/angular.ts, packages/fiddle/package-lock.json
Fix angular parser typescript warnings, fix broken fiddle lock file.
Not really sure why these didn't manifest on CI, only happens when building the CLI locally.
=> Fix warnings

packages/cli/src/__tests__/cli-integration.test.ts
I dunno why this recently broke, was good on main.
=> fix(cli): fix borked test

.bazelignore, .github/workflows/pr-runner.yml, .gitignore, BUILD, WORKSPACE, package-lock.json, package.json, packages/core/BUILD, packages/core/package-lock.json, packages/core/package.json, packages/core/src/__tests__/__snapshots__/qoot.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/generators/qoot.ts, packages/core/src/helpers/is-component.ts, tsconfig.bazel.json
fix(qwik): update generated output to match latest @builder/qwik
- switch from import `qoot` to `@bilder.io/qwik`
- switch to `provideEvent()` from `provideQrlExp('event')
=> fix(qwik): update generated output to match latest @builder/qwik

packages/core/package-lock.json, packages/core/package.json, packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/__snapshots__/parse-jsx.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/builder.test.ts, packages/core/src/generators/builder.ts, packages/core/src/generators/jsx-lite.ts, packages/core/src/generators/react.ts, packages/core/src/helpers/babel-transform.ts, packages/core/src/helpers/create-jsx-lite-component.ts, packages/core/src/helpers/replace-idenifiers.ts, packages/core/src/jsx-types.ts, packages/core/src/parsers/builder.ts, packages/core/src/parsers/jsx.ts, packages/core/src/types/jsx-lite-component.ts, packages/eslint-plugin/src/__tests__/no-conditional-render.ts, packages/eslint-plugin/src/index.ts, packages/eslint-plugin/src/rules/jsx-callback-arg-name.ts, packages/fiddle/src/components/Fiddle.tsx, packages/fiddle/src/constants/templates.ts, packages/fiddle/src/index.tsx
also adds support for inline symbols
=> migrate to subset of React API 

packages/fiddle/src/constants/templates.ts
=> fix(fiddle): fix tailwind template syntax error

README.MD, docs/overview.md
=> fix example codes

packages/fiddle/public/preview.html
could be related to https://github.com/BuilderIO/mitosis/issues/134
=> fix(preview): underine -> underline

packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/__tests__/qwik.test.component-binding.json, packages/core/src/__tests__/qwik.test.ts, packages/core/src/generators/minify.ts, packages/core/src/generators/qwik/component.ts, packages/core/src/generators/qwik/directives.ts, packages/core/src/generators/qwik/jsx.ts, packages/core/src/generators/qwik/src-generator.ts, packages/core/src/generators/react-native.ts, packages/core/src/index.ts, packages/core/src/parsers/builder.ts, packages/core/src/parsers/liquid.ts, packages/core/src/plugins/compile-away-builder-components.ts, packages/core/src/symbols/symbol-processor.ts
- Symbols did not support bindings from parent
- It was not possible to have client based Components
- Created `Image` as a client side component so that it can render
correctly under different bindings.
=> fix(qwik): Fix Symbol bindings

packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/__tests__/qwik.test.component-binding.json, packages/core/src/__tests__/qwik.test.ts, packages/core/src/generators/qwik/component.ts, packages/core/src/generators/qwik/directives.ts, packages/core/src/generators/qwik/src-generator.ts, packages/core/src/parsers/builder.ts, packages/core/src/symbols/symbol-processor.ts
- Symbols did not use `options.data` for props
- We did not extract `options.content.data.state` for Server state.
- `CoreButton` is now render in Qwik
ENG-2210
=> fix(qwik): Include symbol data in component props

packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/generators/qwik/component.ts, packages/core/src/generators/qwik/directives.ts
Fixes https://builder-io.atlassian.net/browse/ENG-2251
=> fix(qwik): don't generate image-sizer if image has content

packages/fiddle/src/constants/templates.ts
=> fix ref example

packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/__snapshots__/context.test.ts.snap, packages/core/src/__tests__/__snapshots__/html.test.ts.snap, packages/core/src/__tests__/__snapshots__/liquid.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/builder.test.ts, packages/core/src/__tests__/data/blocks/builder-render-block.raw.tsx, packages/core/src/__tests__/data/blocks/builder-render-content.raw.tsx, packages/core/src/__tests__/data/blocks/columns.raw.tsx, packages/core/src/__tests__/data/blocks/form.raw.tsx, packages/core/src/__tests__/data/blocks/select.raw.tsx, packages/core/src/__tests__/data/blocks/stamped-io.raw.tsx, packages/core/src/generators/react.ts, packages/core/src/parsers/jsx.ts
Hey! I tried to follow other patterns for this fix, just _always_ add the `index` argument. 
Closes https://github.com/BuilderIO/mitosis/issues/181
=> Add missing "index" in React generator when using For

packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/__snapshots__/html.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/__tests__/data/blocks/stamped-io.raw.tsx, packages/core/src/__tests__/webcomponent.test.ts, packages/core/src/generators/html.ts
=> Fix: Imports for webcomponents is now fixed.

packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/__snapshots__/context.test.ts.snap, packages/core/src/__tests__/__snapshots__/parse-jsx.test.ts.snap, packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/__tests__/qwik.test.component-inputs.json, packages/core/src/__tests__/qwik.test.ts, packages/core/src/generators/qwik/component.ts, packages/core/src/generators/qwik/src-generator.ts, packages/core/src/helpers/create-mitosis-component.ts, packages/core/src/parsers/builder.ts, packages/core/src/types/mitosis-component.ts
Add `inputs` to `MitosisComponents` so that the generated code can
create default state for the generated components.
=> fix(qwik): Add inputs to `MitosisComponents`

packages/cli/package-lock.json, packages/cli/package.json, packages/core/package-lock.json, packages/core/package.json
=> chore: publish core and cli

packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/__tests__/qwik.test.ts, packages/core/src/generators/qwik/component.ts, packages/core/src/generators/qwik/directives.ts, packages/core/src/generators/qwik/handlers.ts, packages/core/src/generators/qwik/jsx.ts, packages/core/src/generators/qwik/src-generator.ts, packages/core/src/generators/qwik/styles.ts
Instead of trying to generate pretty and minified format, the code now
always generates minified format and only runs prettier if requested
by the callee. This keeps the runtime fast for most use cases,
but debugging output friendly.
=> fix(qwik): Use `prettier` for friendly formatting;

packages/core/package.json, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/data/blocks/multiple-onUpdate.raw.tsx, packages/core/src/__tests__/data/blocks/multiple-onUpdateWithDeps.raw.tsx, packages/core/src/__tests__/react-native.test.ts, packages/core/src/__tests__/react.test.ts, packages/core/src/__tests__/svelte.test.ts, packages/core/src/__tests__/vue.test.ts, packages/core/src/generators/angular.ts, packages/core/src/generators/html.ts, packages/core/src/generators/react.ts, packages/core/src/generators/stencil/generate.ts, packages/core/src/generators/svelte.ts, packages/core/src/generators/vue.ts, packages/core/src/helpers/map-refs.ts, packages/core/src/parsers/jsx.ts, packages/core/src/types/mitosis-component.ts
=> allow multiple onUpdate hooks

packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/generators/html.ts
Refactor update function to run user updated code first, then run internal querySelector updates next.
Refactor connectedCallback to run onMounted before update.
=> Fix(webcomponents): issue of bindings/state being missed during update()

README.MD, docs/README.md, docs/components.md, docs/gotchas.md, docs/hooks.md, packages/eslint-plugin/docs/rules/README.md
- add onUpdate docs
- link to ESLint rules in gotchas
=> Docs: onUpdate

packages/cli/mitosis.config.js, packages/cli/src/commands/compile.ts, packages/cli/src/helpers/get-mitosis-config.ts
=> read generator config from mitosis.config.js

.yarnrc.yml, package.json, packages/cli/package.json, yarn.lock
- CLI is missing explicit `dedent` dependency, causing issues when importing it.
=> Fix: CLI deps

packages/cli/src/helpers/get-mitosis-config.ts
fix(cli): add missing .js extension to path
=> fix mitosis.config.js import

README.MD
=> docs(README): fix link typo

packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/angular.test.ts, packages/core/src/__tests__/data/blocks/slot.raw.tsx, packages/core/src/generators/angular.ts
Changed ng slot to ng content. 
https://angular.io/guide/content-projection - I don't think ng-slot exists. I could be wrong though.
=> Fix ng-slot to ng-content.

packages/cli/src/build/build.ts, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/generators/context/solid.ts, packages/core/src/generators/solid.ts, packages/core/src/index.ts
and a minor bug fix
for the solidjs SDK (cc @davedbase)
=> Context support for solidjs

packages/cli/package.json, packages/cli/src/build/build.ts, packages/cli/src/build/helpers/transpile-solid-file.ts, packages/core/package.json, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/generators/solid.ts
similar to vue - we don't want to precompile these so they can compile differently per target (client vs server, etc)
also fixes solidjs index
=> don't transpile solidjs jsx

packages/eslint-plugin/docs/rules/no-var-name-same-as-prop-name.md, packages/eslint-plugin/src/index.ts, packages/eslint-plugin/src/rules/__tests__/no-var-name-same-as-prop-name.ts, packages/eslint-plugin/src/rules/no-var-name-same-as-prop-name.ts
=> fix issue #302

packages/core/src/types/mitosis-node.ts
Fix docs based on feedback from @steve8708
=> improve docs around properties/bindings

packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/angular.test.ts, packages/core/src/__tests__/data/blocks/content-slot.raw.tsx, packages/core/src/__tests__/data/blocks/slot.raw.tsx, packages/core/src/__tests__/react.test.ts, packages/core/src/flow.ts, packages/core/src/generators/angular.ts, packages/core/src/generators/react.ts
#324 
Updates Angular and React with the following proposition.
=> feat(Slot): Slot in component #324

docs/components.md
explaining slot and children
preview link
https://github.com/BuilderIO/mitosis/blob/70f7270c3ea75c47dc3e5e2c616ef3777d9043c5/docs/components.md#children
=> docs(components): Slot/Children

packages/core/package.json
=> publish core

packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/__snapshots__/html.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/generators/html.ts
pass scope around to not lose context
=> fix(webcomponent): pass scope

packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/symbols/symbol-processor.ts
=> fix(qwik): Store state for root component as well

docs/hooks.md
=> docs(useRef): fix import in example

packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/html.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/stencil.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/__tests__/angular.test.ts, packages/core/src/__tests__/data/basic.raw.tsx, packages/core/src/generators/angular.ts, packages/core/src/generators/html.ts, packages/core/src/generators/react.ts, packages/core/src/generators/solid.ts, packages/core/src/generators/stencil/generate.ts, packages/core/src/generators/svelte.ts, packages/core/src/generators/vue.ts, packages/core/src/parsers/jsx.ts
=> feat: support custom event name

packages/core/src/__tests__/__snapshots__/html.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/stencil.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/__tests__/data/blocks/text.raw.tsx, packages/core/src/generators/react.ts
[fix #286 ](https://github.com/BuilderIO/mitosis/issues/286)
[fix #206 ](https://github.com/BuilderIO/mitosis/issues/206)
=> fix: innerHTML does not inject variables

packages/core/src/generators/angular.ts, packages/core/src/generators/html.ts, packages/core/src/generators/liquid.ts, packages/core/src/generators/svelte.ts, packages/core/src/generators/swift-ui.ts, packages/core/src/generators/template.ts, packages/core/src/generators/vue.ts, packages/core/src/helpers/get-styles.ts, packages/core/src/parsers/builder.ts, packages/core/src/parsers/jsx.ts, packages/core/src/plugins/compile-away-builder-components.ts, packages/core/src/types/mitosis-node.ts
=> chore: impove binding type

packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/__tests__/angular.test.ts, packages/core/src/__tests__/svelte.test.ts, packages/core/src/generators/angular.ts
=> fix(innerHTML): angular && svelte

developer/README.md
Add package name of eslint-plugin to the developer docs.
=> docs(developer): add lint package name

packages/core/src/generators/builder.ts, packages/core/src/generators/qwik/jsx.ts, packages/core/src/generators/solid.ts, packages/core/src/generators/svelte.ts, packages/core/src/helpers/collect-styles.ts, packages/core/src/helpers/map-refs.ts
Rendering dynamic tags in SolidJS causes a crash. Regression from #369
=> fix(solid): dynamic this binding

docs/components.md
fixes https://github.com/BuilderIO/mitosis/issues/410
=> docs(components): webcomponent slots

packages/core/src/symbols/symbol-processor.ts
=> fix(qwik): properly handle undefined values

packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/generators/react.ts
Fixes issue
https://github.com/BuilderIO/mitosis/issues/428
=> fix: onInit throwing useEffect not defined

packages/fiddle/src/constants/templates.ts
Update fiddle templates to showcase more variety of `useState` syntax
=> Fiddle: update templates

packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/generators/react.ts
=> Fix React output ref .current "Object is possibly 'undefined'"

docs/hooks.md
=> docs(hooks): forwardRef for React

.eslintrc.js, .yarn/versions/46f8ffda.yml, examples/basic/.eslintignore, examples/basic/.eslintrc.js, examples/basic/package.json, package.json, packages/eslint-plugin/README.md, packages/eslint-plugin/package.json, packages/eslint-plugin/src/configs/recommended.ts, packages/eslint-plugin/src/index.ts, packages/eslint-plugin/src/rules/__tests__/static-control-flow.ts, packages/eslint-plugin/src/rules/index.ts, packages/eslint-plugin/src/rules/static-control-flow.ts, yarn.lock
- Import our ESLint plugin into the `examples/basic`
- Document the recommended approach merged in #313
=> Misc: ESLint plugin testing

packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/__tests__/data/basic-forwardRef-metadata.raw.tsx, packages/core/src/__tests__/data/basic-forwardRef.raw.tsx, packages/core/src/generators/angular.ts, packages/core/src/generators/html.ts, packages/core/src/generators/mitosis.ts, packages/core/src/generators/react.ts
fix: https://github.com/BuilderIO/mitosis/issues/462
fix: https://github.com/BuilderIO/mitosis/issues/424
=> Feat type props fix forward ref type

packages/core/package.json, yarn.lock
=> fix(core): add missing typescript

packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/html.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/stencil.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/__tests__/data/basic.raw.tsx, packages/core/src/helpers/babel-transform.ts
=> fix(Vue): state methods cannot have underscore in name

packages/core/src/__tests__/data/basic-props-destructure.raw.tsx, packages/core/src/__tests__/data/basic-props.raw.tsx
=> fix: swap props test filename

packages/core/src/generators/angular.ts, packages/core/src/generators/html.ts, packages/core/src/generators/mitosis.ts, packages/core/src/generators/react.ts, packages/core/src/generators/solid.ts, packages/core/src/generators/stencil/generate.ts, packages/core/src/generators/vue.ts, packages/core/src/helpers/render-imports.test.ts, packages/core/src/helpers/render-imports.ts, packages/core/src/targets.ts
Closes #446 
- import processing logic was not requiring `Target`.
=> Fix: imports

packages/core/src/index.ts
throw error when using mitosis during runtime
fix: https://github.com/BuilderIO/mitosis/issues/481
=> feat(core): hook error

packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/__tests__/data/basic-props-destructure.raw.tsx, packages/core/src/__tests__/data/basic-props.raw.tsx, packages/core/src/parsers/jsx.ts
=> fix: propsTypesRef not working with destructured props

package.json
Stop excluding fiddle from `ci:build`
=> fix(ci): build fiddle

docs/configuration.md
=> doc: add jsx runtime types doc

packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/html.test.ts.snap, packages/core/src/__tests__/__snapshots__/liquid.test.ts.snap, packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/stencil.test.ts.snap, packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/parsers/jsx.ts
=> fix: string props defined like {"$VAL"} are considered bindings

packages/core/src/generators/react.ts, packages/core/src/generators/solid.ts, packages/core/src/generators/svelte.ts, packages/core/src/helpers/styles/collect-css.ts, packages/core/src/helpers/styles/collect-styled-components.ts, packages/core/src/helpers/styles/helpers.ts
=> refactor: add nodeHasAnyStyles helper

packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/generators/svelte.ts
missing some pre-processing for onUpdate deps array
=> Fix: Svelte onUpdate deps

packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/__tests__/hash-code.test.ts, packages/core/src/generators/qwik/component.ts, packages/core/src/generators/qwik/directives.ts, packages/core/src/generators/qwik/jsx.ts, packages/core/src/generators/qwik/src-generator.ts, packages/core/src/parsers/builder.ts, packages/core/src/symbols/symbol-processor.ts
=> fix(qwik): don't filter  and support decorating Host element

packages/fiddle/package.json, packages/fiddle/src/functions/get-query-param.ts, packages/fiddle/src/functions/set-query-param.ts, yarn.lock
=> feat: add string compression to query params getter and setter

packages/core/src/helpers/render-imports.ts
=> don't import if file ends with .lite

packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/__tests__/hash-code.test.ts, packages/core/src/__tests__/qwik.test.ts, packages/core/src/generators/builder.ts, packages/core/src/generators/qwik/component.ts, packages/core/src/generators/qwik/directives.ts, packages/core/src/generators/qwik/handlers.ts, packages/core/src/generators/qwik/jsx.ts, packages/core/src/parsers/builder.ts, packages/core/src/symbols/symbol-processor.ts, packages/core/tsconfig.json
=> Pr qwik add ids

packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/parsers/builder.ts
=> fix: consistent `bindings: {code: string}`

packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/generators/angular.ts, packages/core/src/helpers/strip-state-and-props-refs.ts
Mitosis generated code for Angular is not able to access inputs, viewchild etc. because it does not append this.{variableName} 
This fix deals with that specific case.
=> (fix/angular):  fix issue with Angular inputs not being accessible

packages/core/src/generators/qwik/component.ts, packages/core/src/generators/qwik/jsx.ts
=> fix(qwik): properly handle empty pages

packages/cli/src/build/build.ts, packages/cli/src/helpers/fast-clone.ts, packages/core/src/generators/qwik/component-generator.ts
=> Fix: Qwik/CLI JSON cloning

packages/cli/package.json, packages/cli/src/build/build.ts, packages/cli/src/build/helpers/extensions.ts, packages/cli/src/build/helpers/transpile.ts, packages/core/package.json, packages/core/src/__tests__/__snapshots__/lit.test.ts.snap, packages/core/src/__tests__/lit.test.ts, packages/core/src/__tests__/shared.ts, packages/core/src/generators/lit/collect-class-string.ts, packages/core/src/generators/lit/generate.ts, packages/core/src/generators/lit/index.ts, packages/core/src/helpers/has.ts, packages/core/src/helpers/render-imports.ts, packages/core/src/index.ts, packages/core/src/targets.ts, packages/fiddle/src/components/Fiddle.tsx
=> Lit support

packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/generators/builder.ts
Which also fixes the Builder fiddle/preview on mitosis.builder.io
=> Fix Mitosis -> Builder

packages/cli/package.json, packages/core/package.json, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/context.test.ts.snap, packages/core/src/__tests__/__snapshots__/lit.test.ts.snap, packages/core/src/__tests__/__snapshots__/marko.test.ts.snap, packages/core/src/__tests__/__snapshots__/parse-jsx.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/generators/angular.ts, packages/core/src/generators/html.ts, packages/core/src/generators/lit/generate.ts, packages/core/src/generators/marko/generate.ts, packages/core/src/generators/mitosis.ts, packages/core/src/generators/qwik/component-generator.ts, packages/core/src/generators/react.ts, packages/core/src/generators/svelte.ts, packages/core/src/parsers/jsx/component-types.ts, packages/core/src/parsers/jsx/jsx.ts, packages/core/src/parsers/jsx/state.ts, packages/core/src/types/mitosis-component.ts
it doesn't provide scoping by default
=> use scoped styles for marko

packages/cli/package.json, packages/cli/src/build/build.ts, packages/core/package.json, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/react.test.ts
Solves issues where TS components try to import from transipled JS which no longer includes types, so bulds fail
=> Don't transpile TS dependencies when outputting TS

packages/cli/package.json, packages/cli/src/build/helpers/transpile.ts, packages/core/package.json, packages/core/src/__tests__/__snapshots__/context.test.ts.snap, packages/core/src/helpers/render-imports.ts
=> add .js to context imports

packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/generators/svelte.ts
Combine svelte imports to clean up the svelte output
Before:
After:
=> fix(svelte): combine svelte imports

docs/components.md
Update [components.md#state](https://github.com/BuilderIO/mitosis/blob/main/docs/components.md#state)
- change `useState` to `useStore`
- update components doc TOC
=> docs(docs): fix components `useState` -> `useStore` & update TOC

packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/generators/vue.ts
Add prettier typescript parser to Vue generator
=> Add prettier ts parser to vue

packages/cli/package.json, packages/core/package.json, packages/core/src/__tests__/__snapshots__/context.test.ts.snap, packages/core/src/__tests__/__snapshots__/marko.test.ts.snap, packages/core/src/__tests__/__snapshots__/parse-jsx.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/stencil.test.ts.snap, packages/core/src/generators/angular.ts, packages/core/src/generators/builder.ts, packages/core/src/generators/html.ts, packages/core/src/generators/liquid.ts, packages/core/src/generators/lit/generate.ts, packages/core/src/generators/marko/generate.ts, packages/core/src/generators/mitosis.ts, packages/core/src/generators/qwik/directives.ts, packages/core/src/generators/react/generator.ts, packages/core/src/generators/solid/index.ts, packages/core/src/generators/stencil/generate.ts, packages/core/src/generators/svelte.ts, packages/core/src/generators/swift-ui.ts, packages/core/src/generators/template.ts, packages/core/src/generators/vue.ts, packages/core/src/helpers/get-bindings.ts, packages/core/src/helpers/nodes/for.ts, packages/core/src/parsers/angular.ts, packages/core/src/parsers/builder.ts, packages/core/src/parsers/jsx/element-parser.ts, packages/core/src/types/mitosis-node.ts
- improve typing around JSX parser, better handling certain JSX spread properties.
- closes #687 
- closes #386
- Fix certain generators no properly handling custom args for For loop
=> Fix: spread jsx & For node

docs/README.md, docs/context.md
Documents context for folks. Closes #697
=> Add context docs

packages/cli/src/build/build.ts, packages/core/src/types/config.ts
This allows configuring a custom parser (a function returning MitosisJSON) and configuring a different file extension.
I am writing a custom parser, which is why I need this :)
=> feat: support configuring a custom parser and file extensions

packages/core/src/__tests__/__snapshots__/vue-composition.test.ts.snap, packages/core/src/generators/vue.ts
=> fix: #700 vue3 composition api does not add computed

packages/core/src/helpers/render-imports.ts
=> point to default of async import

packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/generators/angular.ts
=> fix: Angular slot content invalid HTML

packages/cli/src/build/build.ts
=> remove redundant output

packages/cli/src/build/build.ts
- Fixes 2nd half of https://github.com/BuilderIO/mitosis/issues/736
=> Fix: React & Solid TypeScript output

packages/cli/src/build/build.ts, packages/core/src/generators/vue.ts
- Vue2: add an edge case algorithm that will handle Show siblings nested within a larger Show
=> Improve vue2 nested Shows

packages/cli/src/build/build.ts, packages/cli/src/build/helpers/transpile.ts, packages/core/src/types/config.ts
Replace file extension with target's extension based on the config.
=> fix: replace file extension based on config

packages/cli/package.json, packages/cli/src/build/build.ts, packages/core/package.json, packages/core/src/generators/angular.ts, packages/core/src/generators/vue.ts, packages/eslint-plugin/package.json
- Closes #726
- adds Vue & Angular config overriders via metadata hook or plugins
- fix overrides path logic in cli'
-
=> Feature: inject vue & angular config

packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/generators/angular.ts
- Instead of having values in string moved them to Object
- Now it is in Object and can be more or less better overridden by the user
- Also, touched a bit `imports` generation
=> refactor(angular): angular component metadata generation

packages/cli/package.json, packages/core/package.json, packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/generators/svelte.ts, packages/eslint-plugin/package.json
- fix svelte style injector to handle null/undefined prop
=> fix svelte mitosis_styling fn

packages/cli/src/build/helpers/extensions.ts
- what changes you made,  https://github.com/BuilderIO/mitosis/issues/763
=> feat(cli): add support typescript file extension for react

packages/cli/src/build/build.ts, packages/core/src/flow.ts, packages/core/src/generators/react-native.ts, packages/core/src/generators/react/generator.ts, packages/core/src/index.ts, packages/core/src/types/config.ts
- pass options to react-native generator in `mitosis build`
=> Fix: react-native options

e2e/e2e-qwik/package.json, packages/core/src/symbols/symbol-processor.ts
=> Pr qwik fix

packages/eslint-plugin/docs/rules/only-default-function-and-imports.md, packages/eslint-plugin/src/constants/hooks.ts, packages/eslint-plugin/src/rules/__tests__/only-default-function-and-imports.ts, packages/eslint-plugin/src/rules/only-default-function-and-imports.ts
=> allow useMetaData

packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue-composition.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/generators/svelte.ts, packages/core/src/generators/vue.ts
Add onInit hook to Vue and Svelte
=> feat(core): add on init to vue and svelte

e2e/e2e-app-qwik-output/package.json, e2e/e2e-app/package.json, e2e/e2e-qwik/package.json, packages/core/src/generators/qwik/src-generator.ts, yarn.lock
=> fix(qwik): update to latest qwik version

README.MD
=> docs(README): fix typo

packages/core/src/__tests__/__snapshots__/vue-composition.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/generators/vue/blocks.ts
Closes https://github.com/BuilderIO/mitosis/issues/816
=> fix(core): #816 vue duplicate v bind

packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/generators/svelte.ts, packages/core/src/generators/vue/blocks.ts, packages/core/src/generators/vue/vue.ts, packages/core/src/helpers/plugins/process-code.ts
=> improve Svelte generator

packages/core/src/generators/svelte/blocks.ts, packages/core/src/generators/svelte/helpers.ts, packages/core/src/generators/svelte/index.ts, packages/core/src/generators/svelte/svelte.ts, packages/core/src/generators/svelte/types.ts
- unbundle generator into multiple files
=> unbundle svelte generator

packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/generators/qwik/directives.ts
=> fix(qwik): workaround for Qwik bug

packages/eslint-plugin/docs/rules/prefer-show-over-ternary-operator.md, packages/eslint-plugin/package.json, packages/eslint-plugin/src/rules/__tests__/prefer-show-over-ternary-operator.ts, packages/eslint-plugin/src/rules/prefer-show-over-ternary-operator.ts
=> mitosis-811 added prefer-show-over-ternary-operator rule

packages/cli/src/build/build.ts
- what changes you made,  https://github.com/BuilderIO/mitosis/issues/839
=> fix(cli): build clean only targets directory files

packages/core/src/__tests__/__snapshots__/angular.import.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.mapper.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/generators/angular.ts
=> fix: issue #862

packages/cli/src/build/helpers/transpile.ts
=> fix(cli): transformImports better RegExp for replace extension

packages/core/src/__tests__/__snapshots__/parse-jsx.test.ts.snap, packages/core/src/__tests__/data/blocks/button-with-metadata.raw.tsx, packages/core/src/parsers/jsx/metadata.ts
- any other context that you think might be helpful for someone to better understand what is contained in this pull request.
fix #852
=> fix: allow useMetaData hook to be used multiple times in same component

packages/core/src/__tests__/__snapshots__/parse-jsx.test.ts.snap, packages/core/src/__tests__/data/basic-outputs-meta.raw.tsx, packages/core/src/parsers/jsx/function-parser.ts
=> feat: allow useMetaData hook to be used within component scope

packages/core/src/__tests__/__snapshots__/angular.import.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.mapper.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/html.test.ts.snap, packages/core/src/__tests__/__snapshots__/lit.test.ts.snap, packages/core/src/__tests__/__snapshots__/marko.test.ts.snap, packages/core/src/__tests__/__snapshots__/parse-jsx.test.ts.snap, packages/core/src/__tests__/__snapshots__/preact.test.ts.snap, packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/rsc.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/stencil.test.ts.snap, packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue-composition.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/__tests__/data/basic.raw.tsx, packages/core/src/generators/vue/compositionApi.ts, packages/core/src/helpers/get-state-object-string.ts, packages/core/src/parsers/jsx/function-parser.ts, packages/core/src/types/mitosis-component.ts
=> feat: Vue composition API keep generic types

packages/core/src/__tests__/__snapshots__/vue-composition.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/generators/vue/compositionApi.ts, packages/core/src/generators/vue/optionsApi.ts
=> fix: vue watchers

packages/fiddle/next.config.js, packages/fiddle/package.json, packages/fiddle/src/components/Fiddle/Linter.ts, packages/fiddle/src/components/JsxCodeEditor.tsx, yarn.lock
=> feat: eslint support ts

packages/eslint-plugin/docs/rules/no-var-name-same-as-prop-name.md, packages/eslint-plugin/docs/rules/no-var-name-same-as-state-property.md, packages/eslint-plugin/src/rules/__tests__/no-var-name-same-as-prop-name.ts, packages/eslint-plugin/src/rules/__tests__/no-var-name-same-as-state-property.ts, packages/eslint-plugin/src/rules/no-var-name-same-as-state-property.ts
=> mitosis-891 cover more cases

packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/generators/vue/helpers.ts, packages/core/src/helpers/babel-transform.ts
Fix of the issue [780](https://github.com/BuilderIO/mitosis/issues/780)
=> fix(vue): add this prefix methods for options API #780

packages/core/src/__tests__/__snapshots__/parse-svelte.test.ts.snap, packages/core/src/__tests__/parse-svelte.test.ts, packages/core/src/__tests__/shared.ts, packages/core/src/generators/solid/index.ts
- add tests that store JSON output of `parseSvelte`
=> Tests: parseSvelte

.gitignore, package.json
chore: cache strategy for code format
=> chore: cache strategy for code format

packages/eslint-plugin/docs/rules/no-var-name-same-as-state-property.md, packages/eslint-plugin/src/rules/__tests__/no-var-name-same-as-state-property.ts, packages/eslint-plugin/src/rules/no-var-name-same-as-state-property.ts
=> handled issue #963 cases

packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/generators/svelte/svelte.ts
=> fix Svelte forwarded ref props

packages/eslint-plugin/src/configs/recommended.ts, packages/eslint-plugin/src/rules/__tests__/no-map-function-in-jsx-return-body.ts, packages/eslint-plugin/src/rules/index.ts, packages/eslint-plugin/src/rules/no-map-function-in-jsx-return-body.ts
=> feat(eslint): no map function in jsx return body

packages/eslint-plugin/package.json, packages/eslint-plugin/src/configs/recommended.ts
=> Fix recommended rule

packages/cli/src/build/build.ts
Add liquid, mitosis, stencil and template generator to CLI. Resolve #935.
=> Add liquid, mitosis, stencil and template to CLI

packages/cli/src/build/helpers/extensions.ts, packages/core/src/helpers/replace-identifiers.test.ts
=> Fix extensions

packages/core/src/__tests__/__snapshots__/alpine.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.import.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.mapper.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/html.test.ts.snap, packages/core/src/__tests__/__snapshots__/lit.test.ts.snap, packages/core/src/__tests__/__snapshots__/marko.test.ts.snap, packages/core/src/__tests__/__snapshots__/parse-jsx.test.ts.snap, packages/core/src/__tests__/__snapshots__/preact.test.ts.snap, packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/rsc.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/stencil.test.ts.snap, packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue-composition.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/__tests__/data/default-props/default-props.raw.tsx, packages/core/src/generators/angular.ts, packages/core/src/generators/react/generator.ts, packages/core/src/generators/vue/compositionApi.ts, packages/core/src/generators/vue/optionsApi.ts
Fix https://github.com/BuilderIO/mitosis/issues/985
=> fix(vue): vue default props empty object value

examples/talk/apps/mitosis.config.cjs
Fix example config type notation
=> chore: fix example config type notation

packages/cli/src/build/helpers/overrides.ts
- Fixed https://github.com/BuilderIO/mitosis/issues/1000
=> fix: filename strip extension regexp

packages/cli/src/build/build.ts, packages/cli/src/build/helpers/files.ts, packages/core/src/types/config.ts
- add `exclude` config to exclude files that match a glob
=> CLI: `exclude` glob

packages/eslint-plugin/docs/rules/no-var-name-same-as-state-property.md, packages/eslint-plugin/src/rules/__tests__/no-var-name-same-as-state-property.ts, packages/eslint-plugin/src/rules/no-var-name-same-as-state-property.ts
=> handled function/method params

packages/core/src/__tests__/__snapshots__/stencil.test.ts.snap, packages/core/src/generators/stencil/collect-class-string.ts
Static classes were not being passed to the resulting code. After inspection, it seems that hasStaticClasses was being calculated before adding to the array.
=> fix: calculate hasStaticClasses after they have been aggregated

docs/hooks.md
Added the useStyle hook to the docs. Info taken from these conversations:
https://github.com/BuilderIO/mitosis/pull/758
https://github.com/BuilderIO/mitosis/issues/757
=> Updated hooks.md with useStyle hook

packages/core/src/generators/react/blocks.ts, packages/core/src/generators/react/generator.ts, packages/core/src/generators/react/helpers.ts, packages/core/src/generators/react/index.ts
- move `blocks.ts` out of generator.ts
=> Misc: refactor React code

docs/components.md
- added <Show> else logic documentation
- update toc level
=> docs(components): added <Show> else logic documentation

docs/hooks.md
- add hooks doc onInit useDefaultProps and add import 
- fix TOC level
=> docs(hooks): add hooks doc onInit useDefaultProps and add import

packages/cli/src/__tests__/__snapshots__/cli-integration.test.ts.snap, packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/__snapshots__/context.test.ts.snap, packages/core/src/__tests__/__snapshots__/preact.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/rsc.test.ts.snap, packages/core/src/__tests__/__snapshots__/taro.test.ts.snap, packages/core/src/generators/mitosis.ts, packages/core/src/generators/react-native.ts, packages/core/src/generators/react/generator.ts, packages/core/src/generators/react/types.ts, packages/core/src/generators/rsc.ts, packages/core/src/generators/taro.ts, packages/core/src/helpers/merge-options.ts
=> Refactor: React generator

packages/core/src/generators/react/blocks.ts, packages/core/src/generators/react/generator.ts
- React Native: move ScrollView styles to `contentContainerStyle`
=> Fix/: reactNative scrollview styles

packages/core/src/__tests__/__snapshots__/parse-jsx.test.ts.snap, packages/core/src/__tests__/shared.ts
- generate separate JS & TS snapshots for `parseJsx`
=> Tests: test TS & JS 

packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/generators/qwik/directives.ts
=> fix(qwik): ensure that src-set has size

packages/core/src/__tests__/__snapshots__/qwik.directive.test.ts.snap, packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/__tests__/qwik.directive.test.ts
=> Fix: tests

packages/core/src/__tests__/__snapshots__/alpine.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.import.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.mapper.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/html.test.ts.snap, packages/core/src/__tests__/__snapshots__/liquid.test.ts.snap, packages/core/src/__tests__/__snapshots__/lit.test.ts.snap, packages/core/src/__tests__/__snapshots__/marko.test.ts.snap, packages/core/src/__tests__/__snapshots__/parse-jsx.test.ts.snap, packages/core/src/__tests__/__snapshots__/preact.test.ts.snap, packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/rsc.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/stencil.test.ts.snap, packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/__tests__/__snapshots__/taro.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue-composition.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/__tests__/data/nested-styles.raw.tsx, packages/core/src/helpers/styles/helpers.ts
I added a function to parse CSS keys that cover the edge case where a custom CSS property is present. This function will also allow for covering other edge cases in the future if it's the case.
This PR closes #1107
=> fix: custom CSS properties

packages/core/src/__tests__/__snapshots__/angular.import.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/__snapshots__/context.test.ts.snap, packages/core/src/__tests__/__snapshots__/lit.test.ts.snap, packages/core/src/__tests__/__snapshots__/marko.test.ts.snap, packages/core/src/__tests__/__snapshots__/parse-jsx.test.ts.snap, packages/core/src/__tests__/__snapshots__/preact.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/rsc.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/stencil.test.ts.snap, packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/__tests__/__snapshots__/taro.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue-composition.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/helpers/__snapshots__/render-imports.test.ts.snap, packages/core/src/helpers/render-imports.ts, packages/core/src/parsers/jsx/imports.ts, packages/core/src/types/mitosis-component.ts
- what changes you made  fixed https://github.com/BuilderIO/mitosis/issues/1138
=> feat: preserve type for import types

packages/core/src/generators/vue/vue.ts
- what changes you made,  implement https://github.com/BuilderIO/mitosis/issues/1142
=> feat: vue generator plugin code pre hook support get json

.yarn/versions/27e00e71.yml, .yarn/versions/6ff24e83.yml, packages/cli/package.json, packages/cli/src/build/helpers/context.ts, packages/core/package.json, packages/core/src/generators/context/react.ts
=> Fix/context types react, release

.github/ISSUE_TEMPLATE/feature_request.yaml, package.json
Retry https://github.com/BuilderIO/mitosis/pull/1141
=> Attempt #2: PR template

.yarn/versions/173dde9b.yml, e2e/e2e-app/src/special-tags.lite.tsx, e2e/e2e-app/tests/main.spec.ts, packages/cli/package.json, packages/core/package.json, packages/core/src/generators/vue/blocks.ts
=> Fix: Vue script tag

packages/core/src/generators/alpine/generate.ts, packages/core/src/generators/angular.ts, packages/core/src/generators/html.ts, packages/core/src/generators/lit/generate.ts, packages/core/src/generators/marko/generate.ts, packages/core/src/generators/qwik/component-generator.ts, packages/core/src/generators/qwik/helpers/state.ts, packages/core/src/generators/react/generator.ts, packages/core/src/generators/solid/index.ts, packages/core/src/generators/solid/state/helpers.ts, packages/core/src/generators/stencil/generate.ts, packages/core/src/generators/svelte/svelte.ts, packages/core/src/generators/vue/vue.ts, packages/core/src/helpers/merge-options.ts, packages/core/src/types/metadata.ts
- add ability to pass options for every generator in useMetadata
=> useMetadata: pass parser options

packages/cli/src/__tests__/__snapshots__/cli-integration.test.ts.snap, packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/parsers/builder/builder.ts, packages/core/src/parsers/jsx/__snapshots__/types-identification.test.ts.snap
=> fix attribute name block-id that should be builder-id

.yarn/versions/2a69f5af.yml, packages/cli/package.json, packages/core/package.json, packages/core/src/__tests__/__snapshots__/alpine.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.import.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.mapper.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/html.test.ts.snap, packages/core/src/__tests__/__snapshots__/liquid.test.ts.snap, packages/core/src/__tests__/__snapshots__/lit.test.ts.snap, packages/core/src/__tests__/__snapshots__/marko.test.ts.snap, packages/core/src/__tests__/__snapshots__/parse-jsx.test.ts.snap, packages/core/src/__tests__/__snapshots__/preact.test.ts.snap, packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/rsc.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/stencil.test.ts.snap, packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/__tests__/__snapshots__/taro.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue-composition.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/__tests__/data/basic-boolean-attribute.raw.tsx, packages/core/src/generators/vue/blocks.ts, packages/core/src/generators/vue/helpers.ts, packages/core/src/generators/vue/vue.ts
=> Fix: Vue default slot

packages/core/src/helpers/plugins/process-signals.ts, packages/core/src/helpers/signals/signals.ts, packages/core/src/parsers/jsx/signals.ts
=> Fix: optional signals

.yarn/versions/c62b27f7.yml, packages/cli/package.json, packages/core/package.json, packages/core/src/generators/svelte/svelte.ts, packages/core/src/helpers/typescript-project.ts, packages/core/src/parsers/jsx/__snapshots__/props-types.test.ts.snap, packages/core/src/parsers/jsx/jsx.ts, packages/core/src/parsers/jsx/props-types.test.ts, packages/core/src/parsers/jsx/props-types.ts, packages/core/src/parsers/jsx/signals.test.ts, packages/core/src/parsers/jsx/signals.ts, packages/core/src/types/mitosis-component.ts
=> Feature: Optional props

packages/core/src/__tests__/__snapshots__/vue-composition.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/generators/vue/blocks.ts
=> fix: vue change event

packages/core/package.json, packages/core/src/generators/svelte/blocks.ts, yarn.lock
=> Fix Svelte <style>

packages/cli/src/build/build.ts, packages/cli/src/build/helpers/nullable.ts, packages/core/src/helpers/output.ts
=> Fix commonOptions.ts config

.yarn/versions/b2be75f1.yml, packages/cli/package.json, packages/cli/tsconfig.json, packages/core/package.json, packages/core/src/helpers/typescript-project.ts, packages/core/src/parsers/jsx/jsx.ts, packages/core/src/parsers/jsx/signals.ts, packages/core/src/parsers/jsx/types.ts
=> Fix: CLI ts config

packages/core/src/__tests__/__snapshots__/alpine.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.import.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.mapper.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/__snapshots__/html.test.ts.snap, packages/core/src/__tests__/__snapshots__/liquid.test.ts.snap, packages/core/src/__tests__/__snapshots__/lit.test.ts.snap, packages/core/src/__tests__/__snapshots__/marko.test.ts.snap, packages/core/src/__tests__/__snapshots__/parse-jsx.test.ts.snap, packages/core/src/__tests__/__snapshots__/preact.test.ts.snap, packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/rsc.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/stencil.test.ts.snap, packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/__tests__/__snapshots__/taro.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue-composition.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/__tests__/data/blocks/stamped-io.raw.tsx, packages/core/src/helpers/styles/helpers.ts
by converting a capital first char in a style object key to begin with a dash
=> support vendor prefixed CSS

.yarn/versions/b9512246.yml, packages/cli/package.json, packages/core/package.json, packages/core/src/__tests__/__snapshots__/alpine.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.import.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.mapper.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/html.test.ts.snap, packages/core/src/__tests__/__snapshots__/lit.test.ts.snap, packages/core/src/__tests__/__snapshots__/marko.test.ts.snap, packages/core/src/__tests__/__snapshots__/parse-jsx.test.ts.snap, packages/core/src/__tests__/__snapshots__/preact.test.ts.snap, packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/rsc.test.ts.snap, packages/core/src/__tests__/__snapshots__/stencil.test.ts.snap, packages/core/src/__tests__/__snapshots__/taro.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/generators/helpers/on-mount.ts, packages/core/src/generators/qwik/component-generator.ts, packages/core/src/generators/qwik/src-generator.ts, packages/core/src/generators/react/generator.ts, packages/core/src/helpers/on-event.ts, packages/core/src/index.ts, packages/core/src/parsers/jsx/function-parser.ts, packages/core/src/types/mitosis-component.ts
- wrap qwik event handlers in $
- store event arg name for `onEvent`
- `current?.` for React
- use arrow fn for `onMount`s to preserve `this` scope
=> Fix: qwik events $

packages/core/src/plugins/compile-away-builder-components.ts
causes issues and isn't needed
=> remove negative z index for bg images

README.MD
mark snippet as jsonc to remove red line highlight on github website
=> chore: Update README.MD, format snippet

packages/core/src/helpers/styles/__snapshots__/collect-styled-components.test.ts.snap, packages/core/src/helpers/styles/collect-styled-components.test.ts, packages/core/src/helpers/styles/collect-styled-components.ts
Inserted missing semi colon when forming class name for styled component
=> Inserted missing semi colon when forming class name for styled component

packages/core/src/generators/angular.ts
As during processing of json we are replacing all `"` to `&quot;` this also affects the quotes inside `binding.css` code and converts them to `&quot;`. So when we `json5.parse` them, they are failing as the object string is not a valid json. This `&quot;` works when we are using `style` -> which gets converted to `ngStyle` attribute that handles this correctly, but this only happens when we are using `css` prop in mitosis.
```
{
...
css: {
code: "{color:'var(--text-icon-secondary-black, rgba(29, 36, 51, 0.80))',fontFeatureSettings:\"'clig' off, 'liga' off\",letterSpacing:'0.15px',margin:'auto 0',font:'400 16px/24px Lato, -apple-system, Roboto, Helvetica, sans-serif '}",
},
...
};
```
after this, turns into
```
...
css: {
code: "{...fontFeatureSettings: &quot;'clig' off, 'liga' …
```
=> fix: json parse issue due to `&quot;` replacement in css code

.yarn/versions/1df68f61.yml, packages/cli/package.json, packages/core/package.json, packages/core/src/generators/svelte/blocks.ts
=> fix svelte <script>

.vscode/settings.json, .yarn/versions/db85d6c2.yml, e2e/e2e-app/tests/main.spec.ts, packages/cli/package.json, packages/core/package.json, packages/core/src/__tests__/__snapshots__/preact.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/rsc.test.ts.snap, packages/core/src/__tests__/__snapshots__/taro.test.ts.snap, packages/core/src/generators/react/generator.ts, packages/core/src/generators/react/helpers.ts, packages/core/src/generators/svelte/blocks.ts, yarn.lock
=> fix svelte `on:` for `svelte:element`

.changeset/config.json, .changeset/shiny-drinks-argue.md
=> add changeset

.changeset/config.json
=> fix changeset

.changeset/funny-starfishes-talk.md, .changeset/strange-pillows-love.md, examples/basic/src/blocks/button.lite.tsx, packages/core/src/__tests__/__snapshots__/alpine.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.import.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.mapper.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/context.test.ts.snap, packages/core/src/__tests__/__snapshots__/html.test.ts.snap, packages/core/src/__tests__/__snapshots__/liquid.test.ts.snap, packages/core/src/__tests__/__snapshots__/lit.test.ts.snap, packages/core/src/__tests__/__snapshots__/marko.test.ts.snap, packages/core/src/__tests__/__snapshots__/parse-jsx.test.ts.snap, packages/core/src/__tests__/__snapshots__/preact.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/rsc.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/stencil.test.ts.snap, packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/__tests__/__snapshots__/taro.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue-composition.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/generators/react/blocks.ts, packages/core/src/helpers/filter-empty-text-nodes.ts, packages/core/src/helpers/is-root-text-node.ts, packages/core/src/parsers/jsx/jsx.ts, packages/fiddle/src/components/Fiddle/Fiddle.tsx
Reverts BuilderIO/mitosis#1355
=> Revert "Fix: redundant empty nodes"

.changeset/curly-shirts-bake.md, packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/builder.test.ts, packages/core/src/__tests__/data/builder/slots.json, packages/core/src/generators/react/blocks.ts, packages/core/src/generators/react/generator.ts, packages/core/src/parsers/builder/builder.ts
Fix Buidler->Mitosis JSON generation of Slots
=> Fix: Builder -> Mitosis slots

.github/workflows/publish.yml, package.json
=> fix: ci build step

package.json, packages/starter/package.json
=> Fix: slow CI build publish

.changeset/quick-pans-rush.md, packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/builder.test.ts, packages/core/src/__tests__/data/builder/custom-component-slot-property.json, packages/core/src/generators/react/blocks.ts, packages/core/src/parsers/builder/builder.ts, packages/core/src/types/mitosis-node.ts
This PR updates the way props with Builder elements as values are handled
https://builder-io.atlassian.net/browse/ENG-5332
=> feat(react): update logic for prop slots

.changeset/poor-balloons-drum.md, packages/cli/src/__tests__/__snapshots__/cli-integration.test.ts.snap, packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/__snapshots__/preact.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/rsc.test.ts.snap, packages/core/src/__tests__/__snapshots__/taro.test.ts.snap, packages/core/src/__tests__/builder.test.ts, packages/core/src/__tests__/data/builder/boolean.json, packages/core/src/generators/react/blocks.ts
=> Fix: React shorthand boolean

.changeset/cool-dogs-appear.md, .changeset/healthy-toys-wait.md, .changeset/ninety-coats-clap.md, .changeset/quiet-phones-decide.md, packages/cli/src/build/helpers/context.ts, packages/cli/src/build/helpers/transpile.ts, packages/core/src/__tests__/__snapshots__/angular.import.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.mapper.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/lit.test.ts.snap, packages/core/src/__tests__/__snapshots__/stencil.test.ts.snap, packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue-composition.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/generators/angular/helpers.ts, packages/core/src/generators/angular/index.ts, packages/core/src/generators/context/angular.ts, packages/core/src/helpers/__snapshots__/replace-identifiers.test.ts.snap, packages/core/src/helpers/component-file-extensions.ts, packages/core/src/helpers/get-props.ts, packages/core/src/helpers/replace-identifiers.ts, packages/core/src/index.ts
This PR handles:
- context for angular
- rename extension support for all files in mitosis
- handle props correctly so 'js'/random prop doesn't get added
- handle dynamic components using ngComponentOutlet and templates (supports children)
- handle spread and some other js stuff inside template
- handle template strings inside template using concatenation
**Jira**
https://builder-io.atlassian.net/browse/ENG-5475
=> [v0] angular generator for gen2 angular sdk

packages/cli/package.json
this is quite nice for the metadata on https://www.npmjs.com/package/@builder.io/mitosis-cli page
=> chore(`package.json`): adding `repository` and `homepage` entries

README.MD, packages/starter/template/README.md
=> improve readme

packages/fiddle/src/constants/templates/jsx-templates.ts
=> types: fixed type for `.focus()`

.changeset/forty-wasps-provide.md, packages/core/src/__tests__/__snapshots__/vue-composition.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/generators/vue/types.ts, packages/core/src/generators/vue/vue.ts
=> Vue: add `casing` option

packages/docs/postcss.config.cjs, packages/docs/src/components/code-editor.tsx, packages/docs/src/routes/playground/index.tsx, packages/docs/vite.config.ts
- fix css nesting
- make outputs code editors readOnly
- add mitosis JSON
=> playground improvements

packages/docs/package.json, packages/docs/src/routes/playground/index.tsx, yarn.lock
=> Fix: playground links

.changeset/soft-steaks-push.md, packages/starter/template/library/.eslintrc.cjs
=> Fix/starter: eslint

packages/docs/package.json, packages/docs/vite.config.ts, yarn.lock
=> Docs: use workspace mitosis

packages/docs/adapters/cloudflare-pages/vite.config.ts
=> fix docs build

packages/docs/adapters/cloudflare-pages/vite.config.ts, packages/docs/project.json
=> fix: docs build

packages/docs/src/routes/docs/configuration/index.mdx
- What changes you made: Updated the targets docs
- Why you made them, and: Because they were outdated
=> Update valid output targets

packages/docs/src/components/code-rotator.tsx
i also updates cloudflare to sync `main` branch now with the production site
=> minor code tweaks

.changeset/clever-needles-rule.md, packages/core/src/parsers/builder/builder.ts
Properly pass builder block meta to mitosis node in all cases
=> feat: Add meta data to component mappers in builder.ts

README.MD
Updated the URL for good first issues
It has a better look for first-time contributors when they land into this page.
https://github.com/BuilderIO/mitosis/contribute
=> Updates URL for 'Good First Issues' in README file

.changeset/many-doors-scream.md, packages/core/src/__tests__/__snapshots__/preact.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/rsc.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/taro.test.ts.snap, packages/core/src/generators/solid/index.ts
and fix invalid jsx attribute (it helped prettier, but throws type errors with solid's types)
=> default solidjs to use style-tag styling

.changeset/good-mirrors-sing.md, packages/core/src/__tests__/__snapshots__/preact.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/rsc.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/taro.test.ts.snap, packages/core/src/generators/react/generator.ts, packages/core/src/generators/solid/index.ts
Adds support for `onInit` hook for react and solid
=> `onInit` hook for react and solid

.changeset/few-bulldogs-swim.md, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/data/react-native/twrnc-state-complex-styled-component.raw.tsx, packages/core/src/__tests__/data/react-native/twrnc-state-styled-component.raw.tsx, packages/core/src/__tests__/react-native.test.ts, packages/core/src/generators/react-native/index.ts
- This PR brings support for more complex `twrnc` styling, including state and multiple dynamic vars
- Sometimes we need to style things conditionally, a single string doesn't help. Plus the initial implementation was bugged
=> feat(react-native): more complex twrnc style cases

.changeset/witty-monkeys-dance.md, packages/core/src/__tests__/__snapshots__/angular.import.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.mapper.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.state.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.styles.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/data/angular/two-fors.raw.tsx, packages/core/src/__tests__/test-generator.ts, packages/core/src/generators/angular/index.ts
This PR implements [`trackBy`](https://angular.dev/guide/directives#tracking-items-with-ngfor-trackby) in the angular generator
Jira
https://builder-io.atlassian.net/browse/ENG-6241
=> feat: implement `trackBy` for angular

.changeset/afraid-numbers-protect.md, .changeset/ninety-lies-boil.md, packages/core/src/__tests__/__snapshots__/angular.import.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.mapper.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.state.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.styles.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/generators/angular/index.ts
=> Fix: Angular ngOnChanges

.changeset/neat-stingrays-pretend.md, packages/core/src/__tests__/__snapshots__/angular.import.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.mapper.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.state.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.styles.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/generators/angular/index.ts
Here `ViewChild` should be `ViewContainerRef`
=> fix[angular]: `ViewContainerRef` import

.changeset/short-seahorses-build.md, packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/__tests__/builder.test.ts, packages/core/src/generators/builder.ts, packages/core/src/parsers/builder/builder.ts
fix bugs needed for our interactivity AI
more context if useful: https://www.loom.com/share/6965276d24834af299c73c0bb2a036ea?from_recorder=1&focus_title=1
=> fix builder<->mitosis bindings

.changeset/witty-kiwis-swim.md, packages/core/src/__tests__/__snapshots__/builder.test.ts.snap, packages/core/src/__tests__/builder.test.ts, packages/core/src/generators/builder.ts, packages/core/src/generators/mitosis.ts, packages/core/src/parsers/builder/builder.ts
also verify onMount works as expected
fixes: https://builder-io.atlassian.net/browse/ENG-6546
=> fix index in for loops between mitosis<->builder

.github/workflows/checks.yml
=> split CI tasks

.changeset/config.json
I wasn't able to run `yarn g:changeset`.
The first [solution](https://github.com/changesets/changesets/issues/1055) I found was changing `baseBranch` in `.changeset/config.json`. 
=> chore: update changeset config to work with origin/main

packages/docs/src/routes/docs/customizability/index.mdx
There was outdated [documentation](https://mitosis.builder.io/docs/customizability/#plugins).
=> docs: update customization plugins docs

README.MD
Hey. Additions to the documentation, namely, added a link to the site in the documentation
=> docs: Adding a link to the site in the documentation

CONTRIBUTING.md
=> explain contribution format

.changeset/tiny-elephants-occur.md, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/data/react-native/native-styles.raw.tsx, packages/core/src/__tests__/react-native.test.ts, packages/core/src/generators/react-native/extract-css-var-default-value.ts, packages/core/src/generators/react-native/helpers.ts, packages/core/src/generators/react-native/index.ts, packages/core/src/generators/react-native/sanitize-react-native-block-styles.ts, packages/core/src/generators/react-native/types.ts, packages/core/src/generators/react/generator.ts, packages/core/src/generators/react/types.ts
Adding commonly seen react-native transformations.
=> React Native style Transform

.changeset/pretty-pears-do.md, .github/workflows/checks.yml, packages/core/src/__tests__/__snapshots__/alpine.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.import.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.mapper.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.state.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.styles.test.ts.snap, packages/core/src/__tests__/__snapshots__/angular.test.ts.snap, packages/core/src/__tests__/__snapshots__/html.test.ts.snap, packages/core/src/__tests__/__snapshots__/lit.test.ts.snap, packages/core/src/__tests__/__snapshots__/marko.test.ts.snap, packages/core/src/__tests__/__snapshots__/mitosis.test.ts.snap, packages/core/src/__tests__/__snapshots__/parse-jsx.test.ts.snap, packages/core/src/__tests__/__snapshots__/preact.test.ts.snap, packages/core/src/__tests__/__snapshots__/qwik.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-native.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/__snapshots__/rsc.test.ts.snap, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/stencil.test.ts.snap, packages/core/src/__tests__/__snapshots__/svelte.test.ts.snap, packages/core/src/__tests__/__snapshots__/taro.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue-composition.test.ts.snap, packages/core/src/__tests__/__snapshots__/vue.test.ts.snap, packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap, packages/core/src/__tests__/data/use-target.raw.tsx, packages/core/src/parsers/jsx/state.ts
=> Fix: useTarget + useState

packages/docs/src/routes/docs/components/index.mdx
- What changes you made: fix typo
=> Docs: add backticks after code block

packages/core/src/__tests__/__snapshots__/react-state-builder.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-state-mobx.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-state-solid.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-state-valtio.test.ts.snap, packages/core/src/__tests__/__snapshots__/react-state-variables.test.ts.snap, packages/core/src/__tests__/__snapshots__/react.test.ts.snap, packages/core/src/__tests__/react-state-builder.test.ts, packages/core/src/__tests__/react-state-mobx.test.ts, packages/core/src/__tests__/react-state-solid.test.ts, packages/core/src/__tests__/react-state-valtio.test.ts, packages/core/src/__tests__/react-state-variables.test.ts, packages/core/src/__tests__/react.test.ts
=> add react state tests

packages/core/src/__tests__/builder.test.ts, packages/core/src/__tests__/data/blocks/index-in-for.raw.tsx
=> test: adding failing test

.changeset/spicy-pens-tease.md, packages/core/src/__tests__/__snapshots__/solid.test.ts.snap, packages/core/src/generators/solid/blocks.ts
=> fix: Solid fragments

packages/docs/src/routes/docs/gotchas/index.mdx
Linked the ESLint rules from github.
- Why you made them:
The link on https://mitosis.builder.io/docs/gotchas/ wasn't working
=> docs: ESLint rules

.changeset/calm-yaks-hide.md, packages/starter/template/library/packages/react/tsconfig.json, packages/starter/template/test-apps/react/package.json
=> @template/server-react: upgrade all dependencies to latest

README.MD, packages/docs/src/routes/docs/overview/index.mdx
updated URL to its successor.
we've migrated to a new org lately and that for need to update this reference.
=> docs: updated URL

.changeset/gentle-peas-turn.md, packages/core/src/__tests__/builder.test.ts, packages/core/src/__tests__/data/builder/tag-name.json, packages/core/src/generators/angular/blocks.ts, packages/core/src/generators/vue/blocks.ts, packages/core/src/generators/vue/vue.ts, packages/core/src/helpers/apply-meta-tagname.ts, packages/core/src/helpers/get-tag-name.ts, packages/core/src/plugins/compile-away-builder-components.ts
=> Fix: Vue Builder $tagName

.changeset/friendly-experts-buy.md, packages/core/jsx-runtime.d.ts
chore: update jsx-runtime.d.ts
=> chore: update jsx-runtime.d.ts

.changeset/happy-windows-notice.md, packages/core/src/__tests__/__snapshots__/swift.test.ts.snap, packages/core/src/__tests__/data/swift/single-quotes-replacement.raw.tsx, packages/core/src/__tests__/swift.test.ts, packages/core/src/__tests__/test-generator.ts, packages/core/src/generators/swift/helpers.ts
Fixes the single quote -> double quote conversion for swift code generation.
=> Fix single quote issue in swift generation

packages/docs/src/routes/docs/figma/index.mdx
=> fix: Fusion URLs
